- name: yum install mariadb
  become: yes
  yum:
    state: present
    name:
      - mariadb
      - mariadb-server
  when: mariadb.type == "yum"

- name: dnf module install mariadb
  become: yes
  dnf:
    state: present
    name: '@mariadb{{ ":" ~ mariadb.version if mariadb.version is defined else "" }}'
  when: mariadb.type == 'module'

- name: dnf install maraidb
  become: yes
  dnf:
    state: present
    name:
      - mariadb
      - mariadb-server
  when: mariadb.type in ["dnf", "module"]

- name: apt install mariadb
  become: yes
  apt:
    state: present
    name:
      - mariadb-client
      - mariadb-server
  when: mariadb.type == "apt"

- name: yum install mariadb devel
  become: yes
  yum:
    state: present
    name: mariadb-connector-c-devel
  when: mariadb.type == "yum" and mariadb.dev | default(False)

- name: dnf install mariadb devel
  become: yes
  dnf:
    state: present
    name: mariadb-connector-c-devel
  when: mariadb.type in ["dnf", "module"] and mariadb.dev | default(False)

- name: apt install mariadb devel
  become: yes
  apt:
    state: present
    name: libmariadb-dev
  when: mariadb.type == "apt" and mariadb.dev | default(False)
