- name: dnf module install mariadb
  become: yes
  dnf:
    state: present
    name: '@mariadb:{{ mariadb.version }}'
  when: os_type == "el8" and mariadb.type == "dnf" and mariadb.version

- name: yum install mariadb
  become: yes
  yum:
    state: present
    name:
      - mariadb
      - mariadb-server
  when: mariadb.type == "yum"

- name: dnf install maraidb
  become: yes
  dnf:
    state: present
    name:
      - mariadb
      - mariadb-server
  when: mariadb.type == "dnf"

- name: apt install mariadb
  become: yes
  apt:
    state: present
    name:
      - mariadb-client
      - mariadb-server
  when: mariadb.type == "apt"

- name: yum install mariadb devel
  become: yes
  yum:
    state: present
    name: mariadb-connector-c-devel
  when: mariadb.type == "yum" and mariadb.dev

- name: dnf install mariadb devel
  become: yes
  dnf:
    state: present
    name: mariadb-connector-c-devel
  when: mariadb.type == "dnf" and mariadb.dev

- name: apt install mariadb devel
  become: yes
  apt:
    state: present
    name: libmariadb-dev
  when: mariadb.type == "apt" and mariadb.dev
