- name: set fact mariadb
  set_fact:
    mariadb: '{{ {"type": ansible_pkg_mgr} | combine(mariadb, app.mariadb, recursive=True) }}'

- name: set fact mariadb.socket for el
  set_fact:
    mariadb: '{{ {"socket": "/var/lib/mysql/mysql.sock"} | combine(mariadb) }}'
  when: os_type is match("el")

- name: set fact mariadb.socket for deb
  set_fact:
    mariadb: '{{ {"socket": "/var/run/mysqld/mysqld.sock"} | combine(mariadb) }}'
  when: os_type is match("deb")
