- name: set fact mariadb
  set_fact:
    mariadb: '{{ {"type": ansible_pkg_mgr} | combine(mariadb, app.mariadb, recursive=True) }}'

- name: set fact mariadb file for el7
  set_fact:
    mariadb: '{{ item | combine(mariadb) }}'
  vars:
    item:
      socket: /var/lib/mysql/mysql.sock
      client_cnf: /etc/my.cnf.d/client.cnf
      server_cnf: /etc/my.cnf.d/server.cnf
  when: os_type == "el7"


- name: set fact mariadb file for el
  set_fact:
    mariadb: '{{ item | combine(mariadb) }}'
  vars:
    item:
      socket: /var/lib/mysql/mysql.sock
      client_cnf: /etc/my.cnf.d/client.cnf
      server_cnf: /etc/my.cnf.d/mariadb-server.cnf
  when: os_type in ["el8", "el9"]

- name: set fact mariadb file for deb
  set_fact:
    mariadb: '{{ item | combine(mariadb) }}'
  vars:
    item:
      socket: /var/run/mysqld/mysqld.sock
      client_cnf: /etc/mysql/mariadb.conf.d/50-client.cnf
      server_cnf: /etc/mysql/mariadb.conf.d/50-server.cnf
  when: os_type is match("deb")
