- name: yum install ruby
  become: yes
  yum:
    state: present
    name: ruby

- name: yum install ruby devel
  become: yes
  yum:
    state: present
    name: ruby-devel
  when: ruby.dev | default(False)

- name: yum install ruby modules (gems)
  become: yes
  yum:
    state: present
    name: "rubygem-{{ item }}"
  loop: "{{ ruby.mods | default([]) }}"
  when: ruby.mods is defined

- name: copy .gemrc
  copy:
    src: ../files/.gemrc
    dest: /home/vagrant/.gemrc

- name: set PATH in .bashrc
  blockinfile:
    path: /home/vagrant/.bashrc
    marker: "# {mark} ANSIBLE MANAGED BLOCK bin"
    block: |
      if ! [[ "$PATH" =~ "$HOME/bin:" ]]
      then
          PATH="$HOME/bin:$PATH"
      fi
      export PATH

- name: gem install packages
  gem:
    name: "{{ item }}"
    state: present
  loop: "{{ ruby.gems | default([]) }}"
  when: ruby.gems is defined
