- name: dnf module install redis
  become: true
  dnf:
    state: present
    name: '@redis:{{ redis.version }}'
  when: redis.type == "dnf" and redis.version is defined

- name: yum install redis
  become: true
  yum:
    state: present
    name: redis
  when: redis.type == "yum"

- name: dnf install redis
  become: true
  dnf:
    state: present
    name: redis
  when: redis.type == "dnf"

- name: apt install redis
  become: true
  apt:
    state: present
    name: redis
  when: redis.type == "apt"

- name: yum install redis devel
  become: true
  yum:
    state: present
    name: redis-devel
  when: redis.type == "yum" and redis.dev

- name: dnf install redis devel
  become: true
  dnf:
    state: present
    name: redis-devel
  when: redis.type == "dnf" and redis.dev

# no available
# - name: apt install redis devel
#   become: true
#   apt:
#     state: present
#     name: ...
#   when: redis.type == "apt" and redis.dev
