- name: dnf module install redis
  become: yes
  dnf:
    state: present
    name: '@redis:{{ redis.version }}'
  when: and redis.type == "dnf" and redis.version is defined

- name: yum install redis
  become: yes
  yum:
    state: present
    name: redis
  when: redis.type == "yum"

- name: dnf install redis
  become: yes
  dnf:
    state: present
    name: redis
  when: redis.type == "dnf"

- name: apt install redis
  become: yes
  apt:
    state: present
    name: redis
  when: redis.type == "apt"

- name: yum install redis devel
  become: yes
  yum:
    state: present
    name: redis-devel
  when: redis.type == "yum" and redis.dev

- name: dnf install redis devel
  become: yes
  dnf:
    state: present
    name: redis-devel
  when: redis.type == "dnf" and redis.dev

- name: apt install redis devel
  become: yes
  apt:
    state: present
    name: libredis-dev
  when: redis.type == "apt" and redis.dev
