- name: snap install ruby
  become: yes
  snap:
    state: present
    classic: yes
    name: ruby
    channel: "{{ ruby_version ~ '/' if ruby_version is defined else '' }}stable"

- name: set PATH in .bashrc
  blockinfile:
    path: /home/vagrant/.bashrc
    marker: "# {mark} ANSIBLE MANAGED BLOCK ruby"
    block: |
      if ! [[ "$PATH" =~ "$HOME/.gem/bin:" ]]
      then
          PATH="$HOME/.gem/bin:$PATH"
      fi
      export PATH

- name: copy .gemrc
  copy:
    src: ../files/.gemrc
    dest: /home/vagrant/.gemrc

- name: gem install packages
  gem:
    name: "{{ item }}"
    state: present
  loop:
    - rubocop
    - yard
    - solargraph
