- name: apt install ruby
  become: yes
  apt:
    name: ruby
    state: present

- name: apt install ruby packages
  become: yes
  apt:
    pkg:
      - ruby-dev
      - ruby-bundler

- name: set PATH in .bashrc
  blockinfile:
    path: /home/vagrant/.bashrc
    marker: '# {mark} ANSIBLE MANAGED BLOCK ruby'
    block: |
      GEM_HOME="$HOME/.gem"
      export GEM_HOME
      if ! [[ "$PATH" =~ "$GEM_HOME/bin:" ]]
      then
          PATH="$GEM_HOME/bin:$PATH"
      fi
      export PATH
