- name: apt remove ruby
  become: yes
  apt:
    name: ruby
    state: absent
    autoremove: yes

- name: snap install ruby
  become: yes
  snap:
    name: ruby
    channel: '{{ ruby.version ~ "/" if ruby.version is defined else "" }}stable'
    state: present
    classic: yes

- name: set PATH in .bashrc
  blockinfile:
    path: /home/vagrant/.bashrc
    marker: '# {mark} ANSIBLE MANAGED BLOCK ruby'
    block: |
      GEM_HOME="$HOME/.gem"
      export GEM_HOME
      if ! [[ "$PATH" =~ "$GEM_HOME/bin:" ]]
      then
          PATH="$GEM_HOME/bin:$PATH"
      fi
      export PATH
