- name: dnf module install redis
  become: yes
  dnf:
    state: present
    name: redis

- name: dnf install redis
  become: yes
  dnf:
    state: present
    name: '@redis{{ ":" ~ redis_version if redis_version is defined else "" }}'

- name: start redis 
  become: yes
  systemd:
    name: redis.service
    enabled: yes
    state: started
