# EL8 ではmoduleを有効にしないとインストールできない
- name: dnf module enable 389 Directory Server
  become: yes
  command:
    cmd: dnf module enable -y 389-ds
  when: os_type == "el8" and ds.type == "dnf"

- name: yum install 389 Directory Server
  become: yes
  yum:
    state: present
    name: 389-ds-base
  when: ds.type == "yum"

- name: dnf install 389 Directory Server
  become: yes
  dnf:
    state: present
    name: 389-ds-base
  when: ds.type == "dnf"

- name: apt install 389 Directory Server
  become: yes
  apt:
    state: present
    name: 389-ds-base
  when: ds.type == "apt"
