- name: dnf module enable 389 Directory Server
  become: yes
  command:
    cmd: dnf module enable -y 389-ds
  when: ansible_distribution_major_version == "8"

- name: dnf install 389 Directory Server
  become: yes
  dnf:
    state: present
    name: 389-ds-base
