# 389 DS
# os: el8, el9, ubuntu2004, ubuntu2204

- import_tasks: vars.yml

- import_tasks: install.yml

- import_tasks: setup.yml

- import_tasks: samba.yml
  when: ds.posix is defined and ds.posix == "samba"

- import_tasks: member_of.yml
  when: ds.member

- import_role:
    name: ldap
