# 389 DS
# os: el8, el9

- import_tasks: vars.yml

- import_tasks: install.yml

- import_tasks: setup.yml

- import_tasks: samba.yml

- import_tasks: user_group_person.yml
  when: ds.user_group is defined and ds.user_group == "person"

- import_tasks: user_group_account.yml
  when: ds.user_group is defined and ds.user_group == "account"

- import_tasks: member_of.yml
  when: ds.member_of
