# 389 DS
# os: el8, el9

- import_tasks: vars.yml

- import_tasks: install.yml

- import_tasks: setup.yml

- import_tasks: samba.yml

- import_tasks: ../../posix_person.yml
  when: ds.posix is defined and ds.posix == "person"

- import_tasks: posix_account.yml
  when: ds.posix is defined and ds.posix == "account"

- import_tasks: member_of.yml
  when: ds.member_of

- import_role: ldap
