# member_of プラグイン

- name: dsconf plugin memberof
  become: yes
  command:
    cmd: 'dsconf -D "{{ ldap_auth.bind_dn }}" -w "{{ ldap_auth.bind_pw }}" {{ ldap_auth.server_uri }} plugin memberof enable'

- name: dsctl restart
  become: yes
  command:
    cmd: 'dsctl slapd-localhost restart'
