# member_of プラグイン

- name: dsconf plugin memberof
  become: true
  command:
    cmd: 'dsconf -D "{{ ds.root.dn }}" -w "{{ ds.root.password }}" ldap://localhost plugin memberof enable'

- name: dsctl restart
  become: true
  command:
    cmd: 'dsctl slapd-localhost restart'
