# Sambaスキーマの有効化

- name: dnf install samba
  become: yes
  dnf:
    state: present
    name: samba

- name: copy samba schema
  become: yes
  copy:
    remote_src: yes
    src: /usr/share/doc/samba/LDAP/samba-schema-FDS.ldif
    dest: /etc/dirsrv/slapd-localhost/schema/60samba.ldif

- name: dsctl restart
  become: yes
  command:
    cmd: 'dsctl slapd-localhost restart'
