
- name: dnf install python3-cryptography
  dnf:
    state: present
    name: python3-cryptography


- name: create private key
  openssl_privatekey:
    path: '{{ tls_file.key }}'
    type: ECC
    curve: secp384r1
    mode: '0600'

- name: create csr
  openssl_csr:
    path: '{{ tls_file.cert }}.csr'
    privatekey_path: '{{ tls_file.key }}'
    digest: sha384
    common_name: localhost

- name: create sign crt
  openssl_certificate:
    provider: selfsigned
    selfsigned_digest: sha384
    path: '{{ tls_file.cert }}'
    privatekey_path: '{{ tls_file.key }}'
    csr_path: '{{ tls_file.cert }}.csr'
