# 日本語化

- name: 日本語パッケージインストール dnf
  become: true
  dnf:
    state: present
    name:
      - langpacks-ja
      - glibc-langpack-ja
  when: ansible_pkg_mgr == "dnf"

- name: 日本語パッケージインストール apt
  become: true
  apt:
    state: present
    name: language-pack-ja
  when:
    - ansible_pkg_mgr == "apt"
    - ansible_distribution == "Ubuntu"

- name: 全言語のロケールインストール apt
  become: true
  apt:
    state: present
    name: locales-all
  when:
    - ansible_pkg_mgr == "apt"
    - ansible_distribution == "Debian"

# FIXME: 古い方法
# - name: set locale ja_JP.UTF-8
#   become: true
#   command: update-locale LANG=ja_JP.UTF-8 LANGUAGE=ja_JP

- name: ロケールを日本語に設定
  become: true
  command: localectl set-locale LANG=ja_JP.UTF-8
