# 日本語化

- name: dnf install japanese packages
  become: yes
  dnf:
    state: present
    name:
      - langpacks-ja
      - glibc-langpack-ja
  when: ansible_pkg_mgr == "dnf"

- name: apt install japanese packages
  become: yes
  apt:
    state: present
    name: language-pack-ja
  when: ansible_pkg_mgr == "apt"

# - name: set locale ja_JP.UTF-8
#   become: yes
#   command: update-locale LANG=ja_JP.UTF-8 LANGUAGE=ja_JP

- name: set locale ja_JP.UTF-8
  become: yes
  command: localectl set-locale LANG=ja_JP.UTF-8
