- name: yum update
  become: true
  yum:
    name: '*'
    state: latest
    update_cache: true
  when: ansible_pkg_mgr == "yum"

- name: dnf update
  become: true
  dnf:
    name: '*'
    state: latest
    update_cache: true
  when: ansible_pkg_mgr == "dnf"

- name: apt update
  become: true
  apt:
    name: '*'
    state: latest
    update_cache: true
  when: ansible_pkg_mgr == "apt"
