- set_fact:
    pkg_confs: []

- set_fact:
    pkg_confs: '{{ pkg_confs + ["/etc/yum.conf"] }}'
  when: ansible_pkg_mgr in ["yum", "dnf"]

- set_fact:
    pkg_confs: '{{ pkg_confs + ["/etc/dnf/dnf.conf"] }}'
  when: ansible_pkg_mgr == "dnf"

- name: lineinfile timeout=600
  become: yes
  lineinfile:
    path: '{{ item }}'
    regexp: '^timeout=.*$'
    line: 'timeout=600'
  loop: '{{ pkg_confs }}'

- name: lineinfile proxy
  become: yes
  lineinfile:
    path: '{{ item }}'
    regexp: '^proxy=.*$'
    line: 'proxy={{ proxy.http }}'
  loop: '{{ pkg_confs }}'
  when: proxy.http is defined

