# タイムゾーン設定

- name: SELinuxを許可モードに変更
  become: true
  ansible.posix.selinux:
    policy: targeted
    state: permissive
  when: ansible_os_family == "RedHat"

- name: タイムゾーンをアジア/東京に設定
  become: true
  community.general.timezone:
    name: Asia/Tokyo

- name: SELinuxを強制モードに変更
  become: true
  ansible.posix.selinux:
    policy: targeted
    state: enforcing
  when: ansible_os_family == "RedHat"
