# タイムゾーン設定

- name: Permissive mode SE Linux
  become: true
  selinux:
    policy: targeted
    state: permissive
  when: ansible_os_family == "RedHat"

- name: Set timezone
  become: true
  timezone:
    name: Asia/Tokyo

- name: Enforce SELinux
  become: true
  selinux:
    policy: targeted
    state: enforcing
  when: ansible_os_family == "RedHat"
