# nginx + modsecurity + mruby

- set_fact:
    nginx_src: 'nginx-{{ nginx.version }}'

- name: nginx get source
  get_url:
    url: 'http://nginx.org/download/{{ nginx_src }}.tar.gz'
    dest: '/usr/local/src/{{ nginx_src }}.tar.gz'

- name: nginx unarchive soruce
  unarchive:
    remote_src: yes
    src: '/usr/local/src/{{ nginx_src }}.tar.gz'
    dest: /usr/local/src/

- name: modsecurity-nginx git clone
  git:
    repo: https://github.com/SpiderLabs/ModSecurity-nginx.git
    dest: /usr/local/src/modsecurity-nginx
    version: 'v{{ modsecurity_nginx.version }}'
    force: yes

- name: ngx_mruy git clone
  git:
    repo: https://github.com/matsumotory/ngx_mruby.git
    dest: /usr/local/src/ngx_mruby
    version: 'v{{ ngx_mruby.version }}'

- name: ngx_mruby run configure
  command:
    argv:
      - ./configure
      - '--with-ngx-src-root=/usr/local/src/{{ nginx_src }}'
    chdir: /usr/local/src/ngx_mruby

- name: ngx_mruby run make build_mruby
  command:
    cmd: make build_mruby
    chdir: /usr/local/src/ngx_mruby

- name: ngx_mruby run make generate_gems_config
  command:
    cmd: make generate_gems_config
    chdir: /usr/local/src/ngx_mruby

- name: nginx run configure
  command:
    argv:
      - ./configure
      # - --with-compat
      - --with-debug
      - --with-file-aio
      # - --with-google_perftools_module
      - --with-http_addition_module
      - --with-http_auth_request_module
      # - --with-http_dav_module
      - --with-http_degradation_module
      # - --with-http_flv_module
      # - --with-http_geoip_module
      - --with-http_gunzip_module
      - --with-http_gzip_static_module
      # - --with-http_image_filter_module
      # - --with-http_mp4_module
      # - --with-http_perl_module
      # - --with-http_random_index_module
      - --with-http_realip_module
      - --with-http_secure_link_module
      - --with-http_slice_module
      - --with-http_ssl_module
      - --with-http_stub_status_module
      - --with-http_sub_module
      - --with-http_v2_module
      # - --with-http_xslt_module
      # - --with-mail
      # - --with-mail_ssl_module
      - --with-pcre
      - --with-pcre-jit
      - --with-stream
      - --with-stream_ssl_module
      - --with-stream_ssl_preread_module
      - --with-threads
      - --add-module=/usr/local/src/modsecurity-nginx
      - --add-module=/usr/local/src/ngx_mruby
      - --add-module=/usr/local/src/ngx_mruby/dependence/ngx_devel_kit
    chdir: '/usr/local/src/{{ nginx_src }}'

- name: nginx run make
  command:
    cmd: make
    chdir: '/usr/local/src/{{ nginx_src }}'

- name: nginx run make install
  command:
    cmd: make install
    chdir: '/usr/local/src/{{ nginx_src }}'
