- name: bundle config
  command:
    argv:
      - bundle
      - config
      - set
      - --global
      - '{{ item.name }}'
      - '{{ item.value }}'
  loop:
    - {name: path, value: ~/.local/share/bundle}
    - {name: bin, value: ~/.local/bin}
