- name: gem install packages
  gem:
    name: '{{ item.split("@") | first }}'
    version: '{{ item.split("@") | last if "@" in item else None }}'
    state: present
  loop: '{{ ruby.gems | default([]) }}'
  when: ruby.gems is defined and ruby.type != "rbenv"

- name: gem install packages
  gem:
    name: '{{ item.split("@") | first }}'
    version: '{{ item.split("@") | last if "@" in item else None }}'
    state: present
  loop: '{{ ruby.gems | default([]) }}'
  environment:
    PATH: '~/.rbenv/shims:~/.rbenv/bin:{{ ansible_env.PATH }}'
    RBENV_VERSION: '{{ ruby.version }}'
  when: ruby.gems is defined and ruby.type == "rbenv"
