- name: dnf module install ruby
  become: yes
  dnf:
    state: present
    name: '@ruby:{{ ruby.version }}'
  when: os_type == "el8" and ruby.type == "dnf" and ruby.version

- name: yum install ruby
  become: yes
  yum:
    state: present
    name: ruby
  when: ruby.type == "yum"

- name: dnf install ruby
  become: yes
  dnf:
    state: present
    name: ruby
  when: ruby.type == "dnf"

- name: apt install ruby
  become: yes
  apt:
    state: present
    name: ruby
  when: ruby.type == "apt"

- name: snap install ruby
  become: yes
  snap:
    state: present
    name: node
    channel: '{{ ruby.version ~ "/" if ruby.version is defined else "" }}stable'
    classic: yes
  when: ruby.type == "snap"

- name: yum install ruby devel
  become: yes
  yum:
    state: present
    name: ruby-dev
  when: ruby.type == "yum" and ruby.dev

- name: dnf install ruby
  become: yes
  dnf:
    state: present
    name: ruby-dev
  when: ruby.type == "dnf" and ruby.dev

- name: apt install ruby
  become: yes
  apt:
    state: present
    name: ruby-devel
  when: ruby.type == "apt" and ruby.dev

- name: yum install ruby packages (gems)
  become: yes
  yum:
    state: present
    name: 'rubygem-{{ item }}'
  loop: '{{ ruby.pkgs | default([]) }}'
  when: ruby.type == "yum" and ruby.pkgs is defined

- name: dnf install ruby packages (gems)
  become: yes
  dnf:
    state: present
    name: 'rubygem-{{ item }}'
  loop: '{{ ruby.pkgs | default([]) }}'
  when: ruby.type == "dnf" and ruby.pkgs is defined

- name: apt install ruby packages (gems)
  become: yes
  apt:
    state: present
    name: 'ruby-{{ item }}'
  loop: '{{ ruby.pkgs | default([]) }}'
  when: ruby.type == "apt" and ruby.pkgs is defined
