- name: dnf module install ruby
  become: true
  dnf:
    state: present
    name: '@ruby:{{ ruby.version }}'
  when: ruby.type == "dnf" and ruby.version is defined

- name: yum install ruby
  become: true
  yum:
    state: present
    name: ruby
  when: ruby.type == "yum"

- name: dnf install ruby
  become: true
  dnf:
    state: present
    name: ruby
  when: ruby.type == "dnf"

- name: apt install ruby
  become: true
  apt:
    state: present
    name: ruby
  when: ruby.type == "apt"

- name: snap install ruby
  become: true
  snap:
    state: present
    name: node
    channel: '{{ ruby.version ~ "/" if ruby.version is defined else "" }}stable'
    classic: true
  when: ruby.type == "snap"

- import_tasks: install_rbenv.yml
  when: ruby.type == "rbenv"

- name: yum install ruby devel
  become: true
  yum:
    state: present
    name: ruby-devel
  when: ruby.type == "yum" and ruby.dev

- name: dnf install ruby
  become: true
  dnf:
    state: present
    name: ruby-devel
  when: ruby.type == "dnf" and ruby.dev

- name: apt install ruby
  become: true
  apt:
    state: present
    name: ruby-dev
  when: ruby.type == "apt" and ruby.dev

- name: yum install ruby packages (gems)
  become: true
  yum:
    state: present
    name: '{{ item }}'
  loop: '{{ ruby.pkgs | default([]) }}'
  when: ruby.type == "yum" and ruby.pkgs is defined

- name: dnf install ruby packages (gems)
  become: true
  dnf:
    state: present
    name: '{{ item }}'
  loop: '{{ ruby.pkgs | default([]) }}'
  when: ruby.type == "dnf" and ruby.pkgs is defined

- name: apt install ruby packages (gems)
  become: true
  apt:
    state: present
    name: '{{ item }}'
  loop: '{{ ruby.pkgs | default([]) }}'
  when: ruby.type == "apt" and ruby.pkgs is defined
