# epel
- name: Install epel repository
  become: true
  ansible.builtin.dnf:
    state: present
    name: epel-release

# cloudsmith

- name: Check dnf repolist
  ansible.builtin.command:
    cmd: dnf repolist
  changed_when: false
  register: kea_dnf_repolist

- name: Install isc-kea repository
  ansible.builtin.shell:
    cmd: |
      curl -1sLf \
        'https://dl.cloudsmith.io/public/isc/kea-2-6/setup.rpm.sh' \
       | sudo -E bash
  changed_when: true
  when: kea_dnf_repolist.stdout_lines | select("match", "isc-kea") | length == 0

- name: install kea
  become: yes
  dnf:
    pkg:
      - isc-kea
      - isc-kea-hooks

- name: check mysql db
  become: yes
  community.mysql.mysql_info:
    login_unix_socket: /var/lib/mysql/mysql.sock
    login_user: root
    filter: databases
  register: mysql_info_result

- name: create kea db
  become: yes
  community.mysql.mysql_db:
    login_unix_socket: /var/lib/mysql/mysql.sock
    login_user: root
    state: present
    name: kea
  when: '"kea" not in mysql_info_result.databases'

- name: create kea user
  become: yes
  mysql_user:
    login_unix_socket: /var/lib/mysql/mysql.sock
    login_user: root
    state: present
    name: kea
    host: localhost
    password: keapass
    priv: 'kea.*:ALL'
  when: '"kea" not in mysql_info_result.databases'

- name: kea-admin init
  become: yes
  command:
    cmd: 'kea-admin db-init mysql -u kea -p keapass -n kea'
  when: '"kea" not in mysql_info_result.databases'

- name: kea-admin upgrade
  become: yes
  command:
    cmd: 'kea-admin db-upgrade mysql -u kea -p keapass -n kea'
  when: '"kea" in mysql_info_result.databases'
