# epel
- name: install kea
  become: yes
  dnf:
    pkg:
      - kea

- name: check mysql db
  become: yes
  community.mysql.mysql_info:
    login_unix_socket: /var/lib/mysql/mysql.sock
    login_user: root
    filter: databases
  register: mysql_info_result

- name: create kea db
  become: yes
  community.mysql.mysql_db:
    login_unix_socket: /var/lib/mysql/mysql.sock
    login_user: root
    state: present
    name: kea
  when: '"kea" not in mysql_info_result.databases'

- name: create kea user
  become: yes
  mysql_user:
    login_unix_socket: /var/lib/mysql/mysql.sock
    login_user: root
    state: present
    name: kea
    host: localhost
    password: keapass
    priv: 'kea.*:ALL'
  when: '"kea" not in mysql_info_result.databases'

- name: kea-admin
  become: yes
  command:
    cmd: 'kea-admin db-init mysql -u kea -p keapass -n kea'
  when: '"kea" not in mysql_info_result.databases'
