# debconf による OpenLDAP の設定

- name: debconf shared/organization
  become: yes
  debconf:
    name: slapd
    question: shared/organization
    value: example
    vtype: string

- name: debconf slapd/domain
  become: yes
  debconf:
    name: slapd
    question: slapd/domain
    value: example.jp
    vtype: string

- name: debconf slapd/password
  become: yes
  debconf:
    name: slapd
    question: '{{ item }}'
    value: '{{ openldap.root.password }}'
    vtype: password
  loop:
    - slapd/password1
    - slapd/password2
