- name: yum install openldap-servers
  become: yes
  yum:
    state: present
    name: openldap-servers
  when: openldap.type == "yum"

- name: dnf install openldap-servers
  become: yes
  dnf:
    state: present
    name: openldap-servers
    enablerepo:
      - plus
      - powertools
  when: openldap.type == "dnf"

- name: apt install slapd
  become: yes
  apt:
    state: present
    name: slapd
  when: openldap.type == "apt"

