- name: yum install openldap-servers
  become: true
  yum:
    state: present
    name: openldap-servers
  when: openldap.type == "yum"

# plus
- name: def config-manager set enabled plus
  become: yes
  command:
    cmd: dnf config-manager --set-enabled plus
  when: openldap.type == "dnf"

# TODO: RHEL9系からはpowertoolsはない
# powertools
- name: def config-manager set enabled powertools
  become: yes
  command:
    cmd: dnf config-manager --set-enabled powertools
  ignore_errors: true
  when: openldap.type == "dnf"

- name: dnf install openldap-servers
  become: true
  dnf:
    state: present
    name: openldap-servers
  when: openldap.type == "dnf"

- name: debconf slapd/password dummy password
  become: true
  debconf:
    name: slapd
    question: '{{ item }}'
    value: 'password'
    vtype: password
  loop:
    - slapd/password1
    - slapd/password2
  when: openldap.type == "apt"

- name: apt install slapd
  become: true
  apt:
    state: present
    name: slapd
  when: openldap.type == "apt"
