# OpenLDAP

- import_tasks: vars.yml

- import_tasks: debconf.yml
  when: openldap.type == "apt"

- import_tasks: install.yml

- import_tasks: samba.yml
  when: ds.posix is defined and ds.posix == "samba"

- import_tasks: member_of.yml
  when: ds.member

- import_tasks: restart.yml

- import_role:
    name: ldap
