# OpenLDAP

- import_tasks: vars.yml

- import_tasks: install.yml

# - name: check ldap search
#   ldap_search:
#     dn: '{{ ldap.base }}'
#   args: '{{ ldap.connect }}'
#   ignore_errors: yes
#   register: ldap_base_dn
# - debug:
#     msg: ldap_base_dn

# TODO: 毎回リセット？
- import_tasks: setup.yml

- import_role:
    name: ldap
