# セットアップ

# TODO: 作りかけ

- name: stop slapd service
  become: yes
  systemd:
    name: slapd.service
    state: stopped

- name: delete slapd database
  become: yes
  file:
    path: /var/lib/ldap
    state: absent

- name: delete slapd config
  become: yes
  file:
    path: /etc/
    state: absent

- name: stop slapd service
  become: yes
  file:
    path: /var/tmp/389ds-setup
    state: directory



- name: copy slapd.conf
  copy:
    src: ../files/slapd.ldif
    dest: /etc/openldap/slapd.ldif

- name: copy schema_ext
  copy:
    src: ../files/schema_ext/
    dest: /etc/openldap/schema_ext/

- name: stop slapd
  systemd:
    name: slapd.service
    state: stopped

- name: remove slapd.d
  file:
    path: /etc/openldap/slapd.d
    state: absent

- name: makedir slapd.d
  file:
    path: /etc/openldap/slapd.d
    state: directory
    owner: ldap
    group: ldap
    mode: '0750'

- name: slapadd slapd.conf
  command: /usr/sbin/slapadd -F /etc/openldap/slapd.d/ -n0 -l /etc/openldap/slapd.ldif

- name: chewon slapd.d
  file:
    path: /etc/openldap/slapd.d
    state: directory
    owner: ldap
    group: ldap
    recurse: yes

- name: start slapd
