# セットアップ

- name: stop slapd service
  become: yes
  systemd:
    name: slapd.service
    state: stopped

# - name: delete slapd database
#   become: yes
#   file:
#     path: '{{ openldap.database_dir }}'
#     state: absent

- name: delete slapd config directory
  become: yes
  file:
    path: '{{ openldap.config_dir }}/slapd.d'
    state: absent

- name: copy schema_ext
  become: yes
  copy:
    src: ../files/schema_ext/
    dest: '{{ openldap.config_dir }}/schema_ext/'

- name: copy slapd.ldif
  become: yes
  template:
    src: ../files/slapd.ldif.j2
    dest: '{{ openldap.config_dir }}/slapd.ldif'

- name: make slapd config directory
  become: yes
  file:
    path: '{{ openldap.config_dir }}/slapd.d'
    state: directory

- name: slapdadd slapd.ldif
  become: yes
  command: '/usr/sbin/slapadd -F {{ openldap.config_dir }}/slapd.d -n0 -l {{ openldap.config_dir }}/slapd.ldif'

- name: chown ldap user slapd.d
  become: yes
  file:
    path: '{{ openldap.config_dir }}/slapd.d'
    owner: '{{ openldap.user }}'
    group: '{{ openldap.group }}'
    recurse: yes

- name: start slapd service
  become: yes
  systemd:
    name: slapd.service
    enabled: yes
    state: started
