- name: set fact ldap
  set_fact:
    ldap: '{{ {"type": ansible_pkg_mgr} | combine(ldap, app.openldap, recursive=True) }}'

- name: set fact ds
  set_fact:
    openldap: '{{ ldap }}'



openldap_dnf:
  config_dir: /etc/openldap
  module_dir: /usr/lib64/openldap

openldap_apt:
  config_dir: /etc/ldap
  module_dir: /usr/lib/ldap
