- name: set fact os_type for RedaHat or Rocky
  set_fact:
    os_type: 'el{{ ansible_distribution_major_version }}'
  when: ansible_os_family in ["RedHat", "Rocky"]

- name: set fact os_type for Ubuntu
  set_fact:
    os_type: 'deb{{ (ansible_distribution_major_version | int) // 2 + 1}}'
  when: ansible_distribution == "Ubuntu"

- name: set fact os_type for Debian
  set_fact:
    os_type: 'deb{{ ansible_distribution_major_version }}'
  when: ansible_distribution == "Debian"

- name: check os_type
  debug:
    msg:
      distribution: '{{ ansible_distribution }}'
      distribution_major_version: '{{ ansible_distribution_major_version }}'
      os_family: '{{ ansible_os_family }}'
      os_type: '{{ os_type | default(None) }}'

- name: faile if os_type isnot defined
  fail:
    msg: Unknown OS! The os_type is not defined.
  when: os_type is not defined