- name: apt install mariadb server
  become: yes
  apt:
    state: present
    name: mariadb-server

- name: apt install mariadb devel
  become: yes
  apt:
    state: present
    name: libmariadb-dev
  when: mariadb.dev | default(False)

- name: stop mariadb
  become: yes
  systemd:
    name: mariadb.service
    enabled: yes
    state: stopped

- name: lineinfile 50-client.cnf default-character-set
  become: yes
  lineinfile:
    path: /etc/mysql/mariadb.conf.d/50-client.cnf
    insertafter: '\[client\]'
    regexp: '^default-character-set\s.*$'
    line: 'default-character-set = utf8mb4'

- name: lineinfile 50-server.cnf character-set-server
  become: yes
  lineinfile:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    insertafter: '\[server\]'
    regexp: '^character-set-server\s.*$'
    line: 'character-set-server = utf8mb4'

- name: lineinfile 50-server.cnf cllation-server
  become: yes
  lineinfile:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    insertafter: '\[server\]'
    regexp: '^collation-server\s.*$'
    line: 'collation-server = utf8mb4_general_ci'

- name: start mariadb
  become: yes
  systemd:
    name: mariadb.service
    enabled: yes
    state: started

- name: apt install python mysql for ansible
  become: yes
  apt:
    state: present
    name: python3-pymysql

- name: create admin user
  become: yes
  mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    login_user: root
    state: present
    name: admin
    host: localhost
    password: admin_password
    priv: '*.*:ALL'
