- name: git clone nodokan
  git:
    repo: https://github.com/kue-ipc/nodokan.git
    dest: /home/vagrant/nodokan
    version: dev

- name: bundle install
  command:
    cmd: bash -lic "bundle install"
    chdir: /home/vagrant/nodokan

- name: rails yarn:install
  command:
    cmd: bash -lic "rails yarn:install"
    chdir: /home/vagrant/nodokan

- name: rails db:setup
  command:
    cmd: bash -lic "rails db:setup"
    chdir: /home/vagrant/nodokan
