# 新しいpsychのために必要
# crbは有効化済み
- name: Install libyaml-devel
  become: yes
  dnf:
    name: libyaml-devel

- name: git clone nodokan
  git:
    repo: https://github.com/kue-ipc/nodokan.git
    dest: ~/nodokan
    version: main

# testにもコピーする
- name: copy settings.local.yml
  copy:
    src: settings.local.yml
    dest: '~/nodokan/config/{{ item }}'
    mode: '0644'
  loop:
    - settings.local.yml
    - settings/test.local.yml

# - name: bundle config
#   command:
#     argv:
#       - bundle
#       - config
#       - set
#       - '{{ item.name }}'
#       - '{{ item.value }}'
#     chdir: ~/nodokan
#   loop:
#     - {name: path, value: vendor/bundle}

- name: bundle install
  command:
    argv:
      - bash
      - '-lic'
      - bundle install
    chdir: ~/nodokan

- name: rails yarn:install
  command:
    argv:
      - bash
      - '-lic'
      - bin/rails yarn:install
    chdir: ~/nodokan

- name: check rails db version
  command:
    argv:
      - bash
      - '-lic'
      - bin/rails db:version
    chdir: ~/nodokan
  ignore_errors: yes
  register: rails_db_version_result

- name: rails db:setup
  command:
    argv:
      - bash
      - '-lic'
      - bin/rails db:setup
    chdir: ~/nodokan
  when: rails_db_version_result.rc != 0

- name: rails radius:setup
  command:
    argv:
      - bash
      - '-lic'
      - bin/rails radius:setup
    chdir: ~/nodokan

- name: rails radius:setup
  command:
    argv:
      - bash
      - '-lic'
      - bin/rails radius:setup
    chdir: ~/nodokan
  environment:
    RAILS_ENV: test

# - name: rails kea:setup
#   command:
#     argv:
#       - bash
#       - '-lic'
#       - bin/rails kea:setup
#     chdir: ~/nodokan
