- name: git clone yuzakan
  git:
    repo: https://github.com/kue-ipc/yuzakan.git
    dest: /home/vagrant/yuzakan
    version: dev

- name: bundle install
  command:
    argv:
      - bash
      - '-lic'
      - bundle install
    chdir: /home/vagrant/yuzakan

- name: npm install
  command:
    argv:
      - bash
      - '-lic'
      - npm install
    chdir: /home/vagrant/yuzakan

- name: bundle exec rake build
  command:
    argv:
      - bash
      - '-lic'
      - bundle exec rake build
    chdir: /home/vagrant/yuzakan

- name: bundle exec hanami db prepare
  command:
    argv:
      - bash
      - '-lic'
      - bundle exec hanami db prepare
    chdir: /home/vagrant/yuzakan

- name: bundle exec hanami db prepare for test
  command:
    argv:
      - bash
      - '-lic'
      - bundle exec hanami db prepare
    chdir: /home/vagrant/yuzakan
  environment:
    HANAMI_ENV: test
