- name: apt install rbenv
  become: yes
  apt:
    name: rbenv
    state: present

- name: set rbenv in .bashrc
  blockinfile:
    path: /home/vagrant/.bashrc
    marker: '# {mark} ANSIBLE MANAGED BLOCK ruby'
    block: |
      eval "$(rbenv init - bash)"

- name: make dir rbenv plugins
  file:
    path: /home/vagrant/.rbenv/plugins
    state: directory

- name: git ruby-build
  git:
    repo: https://github.com/rbenv/ruby-build.git
    dest: /home/vagrant/.rbenv/plugins/ruby-build

- name: rbenv install
  shell:
    cmd: 'rbenv install -s {{ ruby_version }}'
    executable: /bin/bash
    creates: '/home/vagrant/.rbenv/versions/{{ ruby_version }}'
  when: ruby_version is defined

- name: rbenv global
  shell:
    cmd: 'rbenv global {{ ruby_version }}'
    executable: /bin/bash
  when: ruby_version is defined

- name: copy .gemrc
  copy:
    src: ../files/.gemrc
    dest: /home/vagrant/.gemrc

- name: gem install packages
  gem:
    name: '{{ item }}'
    state: present
    user_install: no
  loop:
    - rubocop
    - yard
    - solargraph
  when: ruby_version is defined
