- name: dnf install mariadb
  become: yes
  dnf:
    state: present
    name: '@mariadb{{ ":" ~ mariadb.version if mariadb.version is defined else "" }}/server'

- name: dnf install mariadb-devel
  become: yes
  dnf:
    state: present
    name: mariadb-devel

- name: stop mariadb
  become: yes
  systemd:
    name: mariadb.service
    state: stopped

- name: lineinfile client.cnf default-character-set
  become: yes
  lineinfile:
    path: /etc/my.cnf.d/client.cnf
    insertafter: '\[client\]'
    regexp: '^default-character-set\s.*$'
    line: 'default-character-set = utf8mb4'

- name: lineinfile mariadb-server.cnf character-set-server
  become: yes
  lineinfile:
    path: /etc/my.cnf.d/mariadb-server.cnf
    insertafter: '\[server\]'
    regexp: '^character-set-server\s.*$'
    line: 'character-set-server = utf8mb4'

- name: lineinfile mariadb-server.cnf cllation-server
  become: yes
  lineinfile:
    path: /etc/my.cnf.d/mariadb-server.cnf
    insertafter: '\[server\]'
    regexp: '^collation-server\s.*$'
    line: 'collation-server = utf8mb4_general_ci'

- name: start mariadb 
  become: yes
  systemd:
    name: mariadb.service
    enabled: yes
    state: started

- name: dnf install python mysql
  become: yes
  dnf:
    state: present
    name:
      - python3-PyMySQL

- name: create admin user
  become: yes
  mysql_user:
    login_unix_socket: /var/lib/mysql/mysql.sock
    login_user: root
    state: present
    name: admin
    host: localhost
    password: admin_password
    priv: '*.*:ALL'
