- name: ldap entry cn=admin,ou=groups,dc=example,dc=jp
  ldap_entry:
    dn: cn=admin,ou=groups,dc=example,dc=jp
    objectClass:
      - posixGroup
      - top
    attributes:
      gidNumber: 1
      description: administrator
      description;lang-ja: 管理者
  args: '{{ ldap_auth }}'

- name: ldap entry cn=staff,ou=groups,dc=example,dc=jp
  ldap_entry:
    dn: cn=staff,ou=groups,dc=example,dc=jp
    objectClass:
      - posixGroup
      - top
    attributes:
      gidNumber: 10
      description: staff
      description;lang-ja: スタッフ
      memberUid: user01
  args: '{{ ldap_auth }}'

- name: ldap entry cn=user,ou=groups,dc=example,dc=jp
  ldap_entry:
    dn: cn=user,ou=groups,dc=example,dc=jp
    objectClass:
      - posixGroup
      - top
    attributes:
      gidNumber: 100
      description: general user
      description;lang-ja: 一般ユーザー
  args: '{{ ldap_auth }}'

- name: ldap entry uid=admin,ou=people,dc=example,dc=jp
  ldap_entry:
    dn: uid=admin,ou=people,dc=example,dc=jp
    objectClass:
      - account
      - posixAccount
      - sambaSamAccount
      - top
    attributes:
      cn: admin
      userPassword: pass+admin42
      uidNumber: 1
      gidNumber: 1
      homeDirectory: /home/admin
      sambaSID: '1'
  args: '{{ ldap_auth }}'

- name: ldap entry uid=user01,ou=people,dc=example,dc=jp
  ldap_entry:
    dn: uid=user01,ou=people,dc=example,dc=jp
    objectClass:
      - account
      - posixAccount
      - sambaSamAccount
      - top
    attributes:
      cn: user01
      userPassword: pass0001
      uidNumber: 1001
      gidNumber: 100
      homeDirectory: /home/user01
      sambaSID: '1001'
  args: '{{ ldap_auth }}'

- name: ldap entry uid=user02,ou=people,dc=example,dc=jp
  ldap_entry:
    dn: uid=user02,ou=people,dc=example,dc=jp
    objectClass:
      - account
      - posixAccount
      - sambaSamAccount
      - top
    attributes:
      cn: user02
      userPassword: pass0002
      uidNumber: 1002
      gidNumber: 10
      homeDirectory: /home/user02
      sambaSID: '1002'
  args: '{{ ldap_auth }}'

- name: ldap entry uid=user03,ou=people,dc=example,dc=jp
  ldap_entry:
    dn: uid=user03,ou=people,dc=example,dc=jp
    objectClass:
      - account
      - posixAccount
      - sambaSamAccount
      - top
    attributes:
      cn: user03
      userPassword: pass0003
      uidNumber: 1003
      gidNumber: 100
      homeDirectory: /home/user03
      sambaSID: '1003'
  args: '{{ ldap_auth }}'

- name: ldap entry uid=user04,ou=people,dc=example,dc=jp
  ldap_entry:
    dn: uid=user04,ou=people,dc=example,dc=jp
    objectClass:
      - account
      - posixAccount
      - sambaSamAccount
      - top
    attributes:
      cn: user04
      userPassword: pass0004
      uidNumber: 1004
      gidNumber: 100
      homeDirectory: /home/user04
      sambaSID: '1004'
  args: '{{ ldap_auth }}'

- name: ldap entry uid=user05,ou=people,dc=example,dc=jp
  ldap_entry:
    dn: uid=user05,ou=people,dc=example,dc=jp
    objectClass:
      - account
      - posixAccount
      - sambaSamAccount
      - top
    attributes:
      cn: user05
      userPassword: pass0005
      uidNumber: 1005
      gidNumber: 100
      homeDirectory: /home/user05
      sambaSID: '1005'
  args: '{{ ldap_auth }}'

- name: ldap entry uid=user06,ou=people,dc=example,dc=jp
  ldap_entry:
    dn: uid=user06,ou=people,dc=example,dc=jp
    objectClass:
      - account
      - posixAccount
      - sambaSamAccount
      - top
    attributes:
      cn: user06
      userPassword: pass0006
      uidNumber: 1006
      gidNumber: 100
      homeDirectory: /home/user06
      sambaSID: '1006'
  args: '{{ ldap_auth }}'
