# ldap 操作のための python-ldap

- name: yum install python-ldap
  become: yes
  yum:
    state: present
    name: python3-ldap
  when: ansible_pkg_mgr == "yum"

- name: dnf install python-ldap
  become: yes
  dnf:
    state: present
    name: python3-ldap
  when: ansible_pkg_mgr == "dnf"

- name: apt install python-ldap
  become: yes
  apt:
    state: present
    name: python3-ldap
  when: ansible_pkg_mgr == "apt"
