# LDAP共通

- import_tasks: install.yml

- import_tasks: base.yml

- include_tasks: posix_person.yml
  when: ldap.posix is defined and ldap.posix == "person"

- include_tasks: posix_account.yml
  when: ldap.posix is defined and ldap.posix == "account"

- include_tasks: posix_samba.yml
  when: ldap.posix is defined and ldap.posix == "samba"

- include_tasks: member.yml
  when: ldap.member
