# memberofの ユーザーとグループ

- name: member ldap entry ou
  community.general.ldap_entry:
    dn: 'ou={{ item }},{{ ldap.base }}'
    objectClass: '{{ ldap_oc.ou }}'
    attributes:
      ou: '{{ item }}'
  args: '{{ ldap.connect }}'
  loop:
    - User
    - Group

- name: member ldap entry user admin
  community.general.ldap_entry:
    dn: 'cn=admin,ou=User,{{ ldap.base }}'
    objectClass: '{{ ldap_oc.user.member }}'
    attributes:
      cn: admin
      mail: admin@example.jp
      userPassword: pass+admin42
      displayName: Kanri Ichiro
      displayName;lang-ja: 管理　一郎
      sn: Kanri
      sn;lang-ja: 管理
      givenName: Ichiro
      givenName;lang-ja: 一郎
  args: '{{ ldap.connect }}'

- name: member ldap entry user user01
  community.general.ldap_entry:
    dn: 'cn=user01,ou=User,{{ ldap.base }}'
    objectClass: '{{ ldap_oc.user.member }}'
    attributes:
      cn: user01
      mail: user01@example.jp
      userPassword: pass0001
      displayName: Yuza Taro
      displayName;lang-ja: 湯座　太郎
      sn: Yuza
      sn;lang-ja: 湯座
      givenName: Taro
      givenName;lang-ja: 太郎
  args: '{{ ldap.connect }}'

- name: member ldap entry user user02
  community.general.ldap_entry:
    dn: 'cn=user02,ou=User,{{ ldap.base }}'
    objectClass: '{{ ldap_oc.user.member }}'
    attributes:
      cn: user02
      mail: user02@example.jp
      userPassword: pass0002
      displayName: Yuza Jiro
      displayName;lang-ja: 湯座　次郎
      sn: Yuza
      sn;lang-ja: 湯座
      givenName: Jiro
      givenName;lang-ja: 次郎
  args: '{{ ldap.connect }}'

- name: member ldap entry user user03
  community.general.ldap_entry:
    dn: 'cn=user03,ou=User,{{ ldap.base }}'
    objectClass: '{{ ldap_oc.user.member }}'
    attributes:
      cn: user03
      mail: user03@example.jp
      userPassword: pass0003
      displayName: Yuza Hanako
      displayName;lang-ja: 湯座　花子
      sn: Yuza
      sn;lang-ja: 湯座
      givenName: Hanako
      givenName;lang-ja: 花子
  args: '{{ ldap.connect }}'

- name: member ldap entry user user04
  community.general.ldap_entry:
    dn: 'cn=user04,ou=User,{{ ldap.base }}'
    objectClass: '{{ ldap_oc.user.member }}'
    attributes:
      cn: user04
      mail: user04@example.jp
      userPassword: pass0004
      displayName: Nanashi Gonbee
      displayName;lang-ja: 名無し　権兵衛
      sn: Nanashi
      sn;lang-ja: 名無し
      givenName: Gonbee
      givenName;lang-ja: 権兵衛
  args: '{{ ldap.connect }}'

- name: member ldap entry user user05
  community.general.ldap_entry:
    dn: 'cn=user05,ou=User,{{ ldap.base }}'
    objectClass: '{{ ldap_oc.user.member }}'
    attributes:
      cn: user05
      mail: user05@example.jp
      userPassword: pass0005
      displayName: Suzuki Tsuyoshi
      displayName;lang-ja: 鈴木　剛
      sn: Suzuki
      sn;lang-ja: 鈴木
      givenName: Tsuyoshi
      givenName;lang-ja: 剛
  args: '{{ ldap.connect }}'

- name: member ldap entry user user06
  community.general.ldap_entry:
    dn: 'cn=user06,ou=User,{{ ldap.base }}'
    objectClass: '{{ ldap_oc.user.member }}'
    attributes:
      cn: user06
      mail: user06@example.jp
      userPassword: pass0006
      displayName: Suzuki Yoko
      displayName;lang-ja: 鈴木　陽子
      sn: Szuki
      sn;lang-ja: 鈴木
      givenName: Yoko
      givenName;lang-ja: 陽子
  args: '{{ ldap.connect }}'

- name: member ldap entry group admin
  community.general.ldap_entry:
    dn: 'cn=admin,ou=Group,{{ ldap.base }}'
    objectClass: '{{ ldap_oc.group.member }}'
    attributes:
      member:
        - cn=admin,ou=User,{{ ldap.base }}
      description: administrator
      description;lang-ja: 管理者
  args: '{{ ldap.connect }}'

- name: member ldap entry gorup staff
  community.general.ldap_entry:
    dn: 'cn=staff,ou=Group,{{ ldap.base }}'
    objectClass: '{{ ldap_oc.group.member }}'
    attributes:
      member:
        - cn=user01,ou=User,{{ ldap.base }}
        - cn=user02,ou=User,{{ ldap.base }}
      description: staff
      description;lang-ja: スタッフ
  args: '{{ ldap.connect }}'

- name: member ldap entry group user
  community.general.ldap_entry:
    dn: 'cn=user,ou=Group,{{ ldap.base }}'
    objectClass: '{{ ldap_oc.group.member }}'
    attributes:
      member:
        - cn=user01,ou=User,{{ ldap.base }}
        - cn=user03,ou=User,{{ ldap.base }}
        - cn=user04,ou=User,{{ ldap.base }}
        - cn=user06,ou=User,{{ ldap.base }}
      description: general user
      description;lang-ja: 一般ユーザー
  args: '{{ ldap.connect }}'

- name: member ldap entry group other
  community.general.ldap_entry:
    dn: 'cn=other,ou=Group,{{ ldap.base }}'
    objectClass: '{{ ldap_oc.group.member }}'
    attributes:
      member:
        - cn=user04,ou=User,{{ ldap.base }}
        - cn=user05,ou=User,{{ ldap.base }}
      description: other
      description;lang-ja: その他
  args: '{{ ldap.connect }}'


# 大量のユーザーとグループ

- name: member ldap entry many users
  community.general.ldap_entry:
    dn: 'cn=test{{ item }},ou=User,{{ ldap.base }}'
    objectClass: '{{ ldap_oc.user.member }}'
    attributes:
      cn: 'test{{ item }}'
      mail: 'test{{ item }}@example.jp'
      userPassword: 'pass0{{ item }}'
      displayName: Test User
      displayName;lang-ja: テスト　ユーザー
      sn: Test
      sn;lang-ja: テスト
      givenName: User
      givenName;lang-ja: ユーザー
  args: '{{ ldap.connect }}'
  loop: '{{ range(100, 200) | list }}'

- name: member ldap entry many groups
  community.general.ldap_entry:
    dn: 'cn=test{{ item }},ou=Group,{{ ldap.base }}'
    objectClass: '{{ ldap_oc.group.member }}'
    attributes:
      member:
        - cn=test{{ item }},ou=User,{{ ldap.base }}
      description: TestGroup
      description;lang-ja: テストグループ
  args: '{{ ldap.connect }}'
  loop: '{{ range(100, 200) | list }}'
