# Posix users and groups
# user objectClass: account, posixAccount, sambaSamAccount
# smabaSID: S-1-5-21-0-0-0-(uidNumber * 2 + 1000)

- name: posix ldap entry ou
  community.general.ldap_entry:
    dn: 'ou={{ item }},{{ ldap.base }}'
    objectClass: '{{ ldap_oc.ou }}'
    attributes:
      ou: '{{ item }}'
  args: '{{ ldap.connect }}'
  loop:
    - people
    - groups

- name: posix ldap entry group admin
  community.general.ldap_entry:
    dn: 'cn=admin,ou=groups,{{ ldap.base }}'
    objectClass: '{{ ldap_oc.group.posix_samba }}'
    attributes:
      gidNumber: 1
      description: administrator
      description;lang-ja: 管理者
      sambaGroupType: 2
      sambaSID: S-1-5-21-0-0-0-1003
  args: '{{ ldap.connect }}'

- name: posix ldap entry group staff
  community.general.ldap_entry:
    dn: 'cn=staff,ou=groups,{{ ldap.base }}'
    objectClass: '{{ ldap_oc.group.posix_samba }}'
    attributes:
      gidNumber: 10
      description: staff
      description;lang-ja: スタッフ
      memberUid: user01
      sambaGroupType: 2
      sambaSID: S-1-5-21-0-0-0-1021
  args: '{{ ldap.connect }}'

- name: posix ldap entry group user
  community.general.ldap_entry:
    dn: 'cn=user,ou=groups,{{ ldap.base }}'
    objectClass: '{{ ldap_oc.group.posix_samba }}'
    attributes:
      gidNumber: 100
      description: general user
      description;lang-ja: 一般ユーザー
      sambaGroupType: 2
      sambaSID: S-1-5-21-0-0-0-1201
  args: '{{ ldap.connect }}'

- name: posix ldap entry group other
  community.general.ldap_entry:
    dn: 'cn=other,ou=groups,{{ ldap.base }}'
    objectClass: '{{ ldap_oc.group.posix_samba }}'
    attributes:
      gidNumber: 1001
      description: other
      description;lang-ja: その他
      memberUid: user04
      sambaGroupType: 2
      sambaSID: S-1-5-21-0-0-0-3003
  args: '{{ ldap.connect }}'

- name: posix ldap entry user admin
  community.general.ldap_entry:
    dn: 'uid=admin,ou=people,{{ ldap.base }}'
    objectClass: '{{ ldap_oc.user.posix_samba }}'
    attributes:
      cn: admin
      userPassword: pass+admin42
      uidNumber: 1
      gidNumber: 1
      homeDirectory: /home/admin
      sambaSID: 'S-1-5-21-0-0-0-1002'
  args: '{{ ldap.connect }}'

- name: posix ldap entry user user01
  community.general.ldap_entry:
    dn: 'uid=user01,ou=people,{{ ldap.base }}'
    objectClass: '{{ ldap_oc.user.posix_samba }}'
    attributes:
      cn: user01
      userPassword: pass0001
      uidNumber: 1001
      gidNumber: 100
      homeDirectory: /home/user01
      sambaSID: 'S-1-5-21-0-0-0-3002'
  args: '{{ ldap.connect }}'

- name: posix ldap entry user user02
  community.general.ldap_entry:
    dn: 'uid=user02,ou=people,{{ ldap.base }}'
    objectClass: '{{ ldap_oc.user.posix_samba }}'
    attributes:
      cn: user02
      userPassword: pass0002
      uidNumber: 1002
      gidNumber: 10
      homeDirectory: /home/user02
      sambaSID: 'S-1-5-21-0-0-0-3004'
  args: '{{ ldap.connect }}'

- name: posix ldap entry user user03
  community.general.ldap_entry:
    dn: 'uid=user03,ou=people,{{ ldap.base }}'
    objectClass: '{{ ldap_oc.user.posix_samba }}'
    attributes:
      cn: user03
      userPassword: pass0003
      uidNumber: 1003
      gidNumber: 100
      homeDirectory: /home/user03
      sambaSID: 'S-1-5-21-0-0-0-3006'
  args: '{{ ldap.connect }}'

- name: posix ldap entry user user04
  community.general.ldap_entry:
    dn: 'uid=user04,ou=people,{{ ldap.base }}'
    objectClass: '{{ ldap_oc.user.posix_samba }}'
    attributes:
      cn: user04
      userPassword: pass0004
      uidNumber: 1004
      gidNumber: 100
      homeDirectory: /home/user04
      sambaSID: 'S-1-5-21-0-0-0-3008'
  args: '{{ ldap.connect }}'

- name: posix ldap entry user user05
  community.general.ldap_entry:
    dn: 'uid=user05,ou=people,{{ ldap.base }}'
    objectClass: '{{ ldap_oc.user.posix_samba }}'
    attributes:
      cn: user05
      userPassword: pass0005
      uidNumber: 1005
      gidNumber: 1001
      homeDirectory: /home/user05
      sambaSID: 'S-1-5-21-0-0-0-3010'
  args: '{{ ldap.connect }}'

- name: posix ldap entry user user06
  community.general.ldap_entry:
    dn: 'uid=user06,ou=people,{{ ldap.base }}'
    objectClass: '{{ ldap_oc.user.posix_samba }}'
    attributes:
      cn: user06
      userPassword: pass0006
      uidNumber: 1006
      gidNumber: 100
      homeDirectory: /home/user06
      sambaSID: 'S-1-5-21-0-0-0-3012'
  args: '{{ ldap.connect }}'

# 大量のユーザーとグループ

- name: posix ldap entry many users
  community.general.ldap_entry:
    dn: 'uid=test{{ item }},ou=people,{{ ldap.base }}'
    objectClass: '{{ ldap_oc.user.posix_samba }}'
    attributes:
      cn: 'test{{ item }}'
      userPassword: 'pass0{{ item }}'
      uidNumber: '{{ 1000 + item }}'
      gidNumber: 100
      homeDirectory: '/home/test{{ item }}'
      sambaSID: 'S-1-5-21-0-0-0-{{3000 + item * 2}}'
  args: '{{ ldap.connect }}'
  loop: '{{ range(100, 200) | list }}'

- name: posix ldap entry many groups
  community.general.ldap_entry:
    dn: 'cn=test{{ item }},ou=groups,{{ ldap.base }}'
    objectClass: '{{ ldap_oc.group.posix_samba }}'
    attributes:
      gidNumber: '{{ 1000 + item }}'
      memberUid:
        - 'test{{ item }}'
      description: TestGroup
      description;lang-ja: テストグループ
      sambaGroupType: 2
      sambaSID: 'S-1-5-21-0-0-0-{{ 3001 + item * 2 }}'
  args: '{{ ldap.connect }}'
  loop: '{{ range(100, 200) | list }}'
