# Posix users and groups
# user objectClass: account, posixAccount

- name: ldap entry people ou
  ldap_entry:
    dn: 'ou=people,dc=example,dc=jp'
    objectClass:
      - organizationalUnit
      - top
  args: '{{ ldap.connect }}'

- name: ldap entry groups ou
  ldap_entry:
    dn: 'ou=groups,dc=example,dc=jp'
    objectClass:
      - organizationalUnit
      - top
  args: '{{ ldap.connect }}'

- name: ldap entry cn=admin,ou=groups,dc=example,dc=jp
  ldap_entry:
    dn: cn=admin,ou=groups,dc=example,dc=jp
    objectClass:
      - posixGroup
      - top
    attributes:
      gidNumber: 1
      description: administrator
      description;lang-ja: 管理者
  args: '{{ ldap.connect }}'

- name: ldap entry cn=staff,ou=groups,dc=example,dc=jp
  ldap_entry:
    dn: cn=staff,ou=groups,dc=example,dc=jp
    objectClass:
      - posixGroup
      - top
    attributes:
      gidNumber: 10
      description: staff
      description;lang-ja: スタッフ
      memberUid: user01
  args: '{{ ldap.connect }}'

- name: ldap entry cn=user,ou=groups,dc=example,dc=jp
  ldap_entry:
    dn: cn=user,ou=groups,dc=example,dc=jp
    objectClass:
      - posixGroup
      - top
    attributes:
      gidNumber: 100
      description: general user
      description;lang-ja: 一般ユーザー
  args: '{{ ldap.connect }}'

- name: ldap entry uid=admin,ou=people,dc=example,dc=jp
  ldap_entry:
    dn: uid=admin,ou=people,dc=example,dc=jp
    objectClass:
      - account
      - posixAccount
      - top
    attributes:
      cn: admin
      userPassword: pass+admin42
      uidNumber: 1
      gidNumber: 1
      homeDirectory: /home/admin
  args: '{{ ldap.connect }}'

- name: ldap entry uid=user01,ou=people,dc=example,dc=jp
  ldap_entry:
    dn: uid=user01,ou=people,dc=example,dc=jp
    objectClass:
      - account
      - posixAccount
      - top
    attributes:
      cn: user01
      userPassword: pass0001
      uidNumber: 1001
      gidNumber: 100
      homeDirectory: /home/user01
  args: '{{ ldap.connect }}'

- name: ldap entry uid=user02,ou=people,dc=example,dc=jp
  ldap_entry:
    dn: uid=user02,ou=people,dc=example,dc=jp
    objectClass:
      - account
      - posixAccount
      - top
    attributes:
      cn: user02
      userPassword: pass0002
      uidNumber: 1002
      gidNumber: 10
      homeDirectory: /home/user02
  args: '{{ ldap.connect }}'

- name: ldap entry uid=user03,ou=people,dc=example,dc=jp
  ldap_entry:
    dn: uid=user03,ou=people,dc=example,dc=jp
    objectClass:
      - account
      - posixAccount
      - top
    attributes:
      cn: user03
      userPassword: pass0003
      uidNumber: 1003
      gidNumber: 100
      homeDirectory: /home/user03
  args: '{{ ldap.connect }}'

- name: ldap entry uid=user04,ou=people,dc=example,dc=jp
  ldap_entry:
    dn: uid=user04,ou=people,dc=example,dc=jp
    objectClass:
      - account
      - posixAccount
      - top
    attributes:
      cn: user04
      userPassword: pass0004
      uidNumber: 1004
      gidNumber: 100
      homeDirectory: /home/user04
  args: '{{ ldap.connect }}'

- name: ldap entry uid=user05,ou=people,dc=example,dc=jp
  ldap_entry:
    dn: uid=user05,ou=people,dc=example,dc=jp
    objectClass:
      - account
      - posixAccount
      - top
    attributes:
      cn: user05
      userPassword: pass0005
      uidNumber: 1005
      gidNumber: 100
      homeDirectory: /home/user05
  args: '{{ ldap.connect }}'

- name: ldap entry uid=user06,ou=people,dc=example,dc=jp
  ldap_entry:
    dn: uid=user06,ou=people,dc=example,dc=jp
    objectClass:
      - account
      - posixAccount
      - top
    attributes:
      cn: user06
      userPassword: pass0006
      uidNumber: 1006
      gidNumber: 100
      homeDirectory: /home/user06
  args: '{{ ldap.connect }}'
