- name: apt install mariadb
  become: yes
  apt:
    state: present
    name: mariadb-server

- name: apt install libmariadbclient-dev
  become: yes
  apt:
    state: present
    name: libmariadbclient-dev

- name: start mariadb 
  become: yes
  systemd:
    name: mariadb.service
    enabled: yes
    state: started

- name: apt install python mysql
  become: yes
  apt:
    state: present
    name: python3-pymysql

- name: create admin user
  become: yes
  mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    login_user: root
    state: present
    name: admin
    host: localhost
    password: admin_password
    priv: '*.*:ALL'
