- name: dnf module install nodejs
  become: true
  dnf:
    state: present
    name: '@nodejs:{{ nodejs.version }}'
  when: nodejs.type == "dnf" and nodejs.version is defined

- name: yum install nodejs
  become: true
  yum:
    state: present
    name:
      - nodejs
      - npm
  when: nodejs.type == "yum"

- name: dnf install nodejs
  become: true
  dnf:
    state: present
    name:
      - nodejs
      - npm
  when: nodejs.type == "dnf"

- name: apt install nodejs
  become: true
  apt:
    state: present
    name:
      - nodejs
      - npm
  when: nodejs.type == "apt"

- name: snap install nodejs
  become: true
  snap:
    state: present
    name: node
    channel: '{{ nodejs.version ~ "/" if nodejs.version is defined else "" }}stable'
    classic: true
  when: nodejs.type == "snap"

# TODO: use 'get_url' or 'uri'
- name: add nodesource repository
  become: true
  shell:
    cmd: 'curl -fsSL https://deb.nodesource.com/setup_{{ nodejs.version if nodejs.version is defined else "lts" }}.x | bash -'
  when: nodejs.type == "nodesource"

- name: apt install nodejs
  become: true
  apt:
    name: nodejs
    state: present
  when: nodejs.type == "nodesource" and ansible_pkg_mgr == "apt"
