- name: Set npm config prefix
  command:
    cmd: npm config set prefix=~/.local

- name: Install npm packages
  npm:
    state: present
    global: true
    name: '{{ item }}'
  loop: '{{ nodejs.npms | default([]) }}'
  when: nodejs.npms is defined

- name: Install npm corepack package
  npm:
    state: present
    global: true
    name: corepack
  loop: '{{ nodejs.npms | default([]) }}'
  when: nodejs.yarn | default(false)

- name: Run corepack enable on shell
  ansible.builtin.shell:
    cmd: . ~/.bashrc && corepack enable
    executable: /bin/bash
  when: nodejs.yarn | default(false)

- name: Run yarn version on shell once again
  ansible.builtin.shell:
    cmd: . ~/.bashrc && yarn --version
    executable: /bin/bash
    stdin: "y\n"
  when: nodejs.yarn | default(false)
