# アプリケーション

# apps:
#   - ds
#   - git
#   - mariadb
#   - nginx
#   - nodejs
#   - openldap
#   - postgresql
#   - redis
#   - ruby
#   - samba

- name: include role for app
  include_role:
    name: '{{ app_name }}'
  loop: '{{ app | dict2items | map(attribute="key") | list }}'
  loop_control:
    loop_var: app_name
