# freeradius-mysql は CRB
- name: def config-manager set enabled crb
  become: yes
  command:
    cmd: dnf config-manager --set-enabled crb
  changed_when: true

- name: install freeradius
  become: yes
  dnf:
    pkg:
      - freeradius
      - freeradius-mysql
      - freeradius-ldap

- name: check mysql db
  become: yes
  community.mysql.mysql_info:
    login_unix_socket: /var/lib/mysql/mysql.sock
    login_user: root
    filter: databases
  register: mysql_info_result

- name: create radius db
  become: yes
  community.mysql.mysql_db:
    login_unix_socket: /var/lib/mysql/mysql.sock
    login_user: root
    state: present
    name: radius
  when: '"radius" not in mysql_info_result.databases'

- name: mysql setup.sql
  become: yes
  shell:
    cmd: 'mysql -u root < /etc/raddb/mods-config/sql/main/mysql/setup.sql'
  when: '"radius" not in mysql_info_result.databases'

- name: mysql scheme.sql
  become: yes
  shell:
    cmd: 'mysql -u root radius < /etc/raddb/mods-config/sql/main/mysql/schema.sql'
  when: '"radius" not in mysql_info_result.databases'
