- name: dnf install redis
  become: yes
  dnf:
    state: present
    name: redis

- name: dnf install redis devel
  become: yes
  dnf:
    state: present
    name: redis-devel
  when: redis.dev | default(False)

- name: start redis 
  become: yes
  systemd:
    name: redis.service
    enabled: yes
    state: started
