- name: git config {{ name }}
  git_config:
    scope: global
    name: 'user.{{ item.key }}'
    value: '{{ item.value }}'
  loop: '{{ git.config[name] | dict2items }}'
  when: git.config[name] is defined
