- name: copy OpenLDAP setup files
  become: yes
  copy:
    src: ../files/
    dest: /var/tmp/openldap-setup/

- name: debconf shared/organization
  become: yes
  debconf:
    name: slapd
    question: shared/organization
    value: example
    vtype: string

- name: debconf slapd/domain
  become: yes
  debconf:
    name: slapd
    question: slapd/domain
    value: example.jp
    vtype: string

- name: debconf slapd/password
  become: yes
  debconf:
    name: slapd
    question: '{{ item }}'
    value: admin_password
    vtype: password
  loop:
    - slapd/password1
    - slapd/password2

- name: apt install slapd
  become: yes
  apt:
    name: slapd
    state: present

- name: start slapd
  become: yes
  systemd:
    name: slapd.service
    enabled: yes
    state: started

- name: apt install pkgs for ldap
  become: yes
  apt:
    pkg:
      - ldap-utils
      - python3-ldap

- name: ldap entry people ou
  ldap_entry:
    server_uri: 'ldap://localhost'
    bind_dn: 'cn=admin,dc=example,dc=jp'
    bind_pw: 'admin_password'
    state: present
    dn: 'ou=people,dc=example,dc=jp'
    objectClass:
      - organizationalUnit
      - top

- name: ldap entry groups ou
  ldap_entry:
    server_uri: 'ldap://localhost'
    bind_dn: 'cn=admin,dc=example,dc=jp'
    bind_pw: 'admin_password'
    state: present
    dn: 'ou=groups,dc=example,dc=jp'
    objectClass:
      - organizationalUnit
      - top

- name: check slapcat
  become: yes
  command:
    cmd: slapcat
  register: slapcat_result

- name: ldapadd
  become: yes
  command:
    argv:
      - ldapadd
      - -x
      - -h
      - localhost
      - -p
      - '389'
      - -D
      - 'cn=admin,dc=example,dc=jp'
      - -w
      - admin_password
      - -f
      - /var/tmp/openldap-setup/user_group.ldif'
  when: 'not "dn: uid=admin,ou=people,dc=example,dc=jp" in slapcat_result.stdout_lines'
