- name: apt remove nodejs
  become: yes
  apt:
    name: nodejs
    state: absent
    autoremove: yes

- name: snap install nodejs
  become: yes
  snap:
    name: node
    channel: "{{ nodejs_version ~ '/' if nodejs_version is defined else '' }}stable"
    state: present
    classic: yes
