# TODO: use 'get_url' or 'uri'

- name: add nodesource repository
  become: yes
  shell:
    cmd: 'curl -fsSL https://deb.nodesource.com/setup_{{ nodejs.version if nodejs.version is defined else "lts" }}.x | bash -'

- name: apt install nodejs
  become: yes
  apt:
    name: nodejs
    state: present
