- name: dnf module install nginx
  become: yes
  dnf:
    state: present
    name: '@nginx:{{ nginx.version }}'
  when: os_type == "el8" and nginx.type == "dnf" and nginx.version is defined

- name: yum install nginx
  become: yes
  yum:
    state: present
    name: nginx
  when: nginx.type == "yum"

- name: dnf install nginx
  become: yes
  dnf:
    state: present
    name: nginx
  when: nginx.type == "dnf"

- name: apt install nginx
  become: yes
  apt:
    state: present
    name: nginx
  when: nginx.type == "apt"
