- name: lineinfile timeout=600
  become: yes
  lineinfile:
    path: '{{ item }}'
    regexp: '^timeout=.*$'
    line: 'timeout=600'
  loop:
    - /etc/yum.conf

- name: lineinfile proxy
  become: yes
  lineinfile:
    path: '{{ item }}'
    regexp: '^proxy=.*$'
    line: 'proxy={{ proxy.http }}'
  loop:
    - /etc/yum.conf
  when: proxy.http is defined

- name: yum update
  become: yes
  yum:
    name: '*'
    state: latest

- name: set locale ja_JP.UTF-8
  become: yes
  command: localectl set-locale LANG=ja_JP.UTF-8

- name: set fs.inotify.max_user_watches 524288 in sysctl
  become: yes
  sysctl:
    name: fs.inotify.max_user_watches
    value: '524288'

- name: yum install other packages
  become: yes
  yum:
    state: present
    name: '{{ item }}'
  loop: '{{ setup.pkgs | default([]) }}'
  when: setup.pkgs is defined
