mariadb:
  dev: false
  admin:
    name: admin
    password: admin_password
mariadb_types:
  yum:
    socket: /var/lib/mysql/mysql.sock
    client_cnf: /etc/my.cnf.d/client.cnf
    server_cnf: /etc/my.cnf.d/server.cnf
  dnf:
    socket: /var/lib/mysql/mysql.sock
    client_cnf: /etc/my.cnf.d/client.cnf
    server_cnf: /etc/my.cnf.d/mariadb-server.cnf
  apt:
    socket: /var/run/mysqld/mysqld.sock
    client_cnf: /etc/mysql/mariadb.conf.d/50-client.cnf
    server_cnf: /etc/mysql/mariadb.conf.d/50-server.cnf

