- name: チェック
  hosts: all
  gather_facts: true
  tasks:
    - name: 変数check_factsを設定
      set_fact:
        check_facts:
          distribution: '{{ ansible_distribution }}'
          distribution_major_version: '{{ ansible_distribution_major_version }}'
          distribution_version: '{{ ansible_distribution_version }}'
          os_family: '{{ ansible_os_family }}'
          pkg_mgr: '{{ ansible_pkg_mgr }}'
    - name: デバッグメッセージ
      debug:
        var: check_facts
