- hosts: all
  roles:
    - setup
    - role: ds
      when:
        ds is defined and
        ansible_os_family in ["RedHat", "Rocky"] and
        ansible_destribution_major_version in ["8", "9"]
    - role: git
      when: git is defined
    - role: mariadb
      when: mariadb is defined
    - role: nginx
      when: nginx is defined
    - role: nodejs
      when: nodejs is defined
    - role: redis
      when: redis is defined
    - role: ruby
      when: ruby is defined
