- hosts: all
  roles:
    - setup
    - role: ds
      when:
        ds is defined and
        ansible_os_family in ["RedHat", "Rocky"] and
        ansible_distribution_major_version in ["8", "9"]
    - role: git
      when: git is defined
    - role: mariadb
      when: mariadb is defined
    - role: nginx
      when: nginx is defined
    - role: nodejs
      when: nodejs is defined
    - role: openldap
      when:
        openldap is defined and (
          ansible_os_family == "Debian" or (
            ansible_os_family == "RedHat" and
            ansible_distribution_major_version == "7"
          )
    - role: redis
      when: redis is defined
    - role: ruby
      when: ruby is defined
