- name: dnf install ruby
  become: yes
  dnf:
    state: present
    name: '@ruby{{ ":" ~ ruby.version if ruby.version is defined else "" }}'

- name: dnf install ruby devel
  become: yes
  dnf:
    state: present
    name: ruby-devel
  when: ruby.dev | default(False)

- name: dnf install ruby modules (gems)
  become: yes
  dnf:
    state: present
    name: 'rubygem-{{ item }}'
  loop: '{{ ruby.pkgs | default([]) }}'
  when: ruby.pkgs is defined

- name: set PATH and GEM_HOME in .bashrc
  blockinfile:
    path: /home/vagrant/.bashrc
    marker: '# {mark} ANSIBLE MANAGED BLOCK ruby'
    block: |
      GEM_HOME="$HOME/.gem/ruby"
      export GEM_HOME
      if ! [[ "$PATH" =~ "$GEM_HOME/bin:" ]]
      then
          PATH="$GEM_HOME/bin:$PATH"
      fi
      export PATH

- name: copy .gemrc
  copy:
    src: ../files/.gemrc
    dest: /home/vagrant/.gemrc

- debug:
    msg: '{{ "rubocop@1.28.2" | split("@") }}'

- name: gem install packages
  gem:
    name: '{{ item | split("@") | first }}'
    version: '{{ item | split("@") | first if "@" in item }}'
    state: present
  loop: '{{ ruby.gems | default([]) }}'
  when: ruby.gems is defined
