- name: dnf module install ruby
  become: yes
  dnf:
    state: present
    name: '@ruby{{ ":" ~ ruby.version if ruby.version is defined else "" }}'

- name: dnf install ruby devel
  become: yes
  dnf:
    state: present
    name: ruby-devel
  when: ruby.dev | default(False)

- name: dnf install ruby modules (gems)
  become: yes
  dnf:
    state: present
    name: 'rubygem-{{ item }}'
  loop: '{{ ruby.pkgs | default([]) }}'
  when: ruby.pkgs is defined

