- name: dnf install python psycopg2 for ansible
  become: true
  dnf:
    state: present
    name: python3-psycopg2
  when: ansible_pkg_mgr == "dnf"

- name: apt install python psycopg2 for ansible
  become: true
  apt:
    state: present
    name: python3-psycopg2
  when: ansible_pkg_mgr == "apt"

- name: create admin user
  become: true
  become_user: postgres
  community.postgresql.postgresql_user:
    login_unix_socket: '{{ postgresql.socket }}'
    login_user: postgres
    state: present
    name: '{{ postgresql.admin.name }}'
    password: '{{ postgresql.admin.password }}'
    role_attr_flags: SUPERUSER

- name: create vagrant user
  become: true
  become_user: postgres
  community.postgresql.postgresql_user:
    login_unix_socket: '{{ postgresql.socket }}'
    login_user: postgres
    state: present
    name: vagrant
    role_attr_flags: SUPERUSER

- name: create database for vagrant user
  become: true
  become_user: postgres
  community.postgresql.postgresql_db:
    login_unix_socket: '{{ postgresql.socket }}'
    login_user: postgres
    state: present
    name: vagrant
