- name: yum install python mysql for ansible
  become: yes
  yum:
    state: present
    name: python2-PyMySQL
  when: ansible_pkg_mgr == "yum"

- name: dnf install python mysql for ansible
  become: yes
  dnf:
    state: present
    name: python3-PyMySQL
  when: ansible_pkg_mgr == "dnf"

- name: apt install python mysql for ansible
  become: yes
  apt:
    state: present
    name: python-pymysql
  when: ansible_pkg_mgr == "apt" and os_type == "deb10"

- name: apt install python mysql for ansible
  become: yes
  apt:
    state: present
    name: python3-pymysql
  when: ansible_pkg_mgr == "apt" and os_type != "deb10"

- name: create admin user
  become: yes
  mysql_user:
    login_unix_socket: '{{ postgresql.socket }}'
    login_user: root
    state: present
    name: '{{ postgresql.admin.name }}'
    host: localhost
    password: '{{ postgresql.admin.password }}'
    priv: '*.*:ALL'
