# cnf

- name: initdb postgresql
  become: true
  command:
    cmd: postgresql-setup --initdb
    creates: "{{ postgresql.datadir }}/PG_VERSION"


- name: lineinfile pg_hba.cnf loopback md5
  become: true
  lineinfile:
    path: "{{ postgresql.datadir }}/pg_hba.conf"
    regexp: '^\s*host\s+all\s+all\s+127.0.0.1/32\s.*$'
    line: "host all all 127.0.0.1/32 md5"

# - name: lineinfile pg_hba.cnf host all md5
#   become: true
#   lineinfile:
#     path: '{{ postgresql.datadir }}/pg_hba.conf'
#     regexp: '^\s*host\s+all\s+all\s+all\s+md5\s*(#.*)?$'
#     line: 'host all all all md5'

# - name: lineinfile postgresql.conf host all md5
#   become: true
#   lineinfile:
#     path: '{{ postgresql.datadir }}/postgresql.conf'
#     regexp: '^#?\s*listen_addresses\s*=.*$'
#     line: "listen_addresses = '*'\t# what IP address(es) to listen on;"
