# cnf

- name: lineinfile client.cnf default-character-set
  become: yes
  lineinfile:
    path: '{{ postgresql.client_cnf }}'
    insertafter: '\[client\]'
    regexp: '^default-character-set\s.*$'
    line: 'default-character-set = utf8mb4'

- name: lineinfile server.scnf character-set-server
  become: yes
  lineinfile:
    path: '{{ postgresql.server_cnf }}'
    insertafter: '\[server\]'
    regexp: '^character-set-server\s.*$'
    line: 'character-set-server = utf8mb4'

- name: lineinfile server.cnf cllation-server
  become: yes
  lineinfile:
    path: '{{ postgresql.server_cnf }}'
    insertafter: '\[server\]'
    regexp: '^collation-server\s.*$'
    line: 'collation-server = utf8mb4_general_ci'
