- name: set fact postgresql
  set_fact:
    postgresql: '{{ {"type": ansible_pkg_mgr} | combine(postgresql, app.postgresql, recursive=True) }}'

- name: set fact postgresql file for el7
  set_fact:
    postgresql: '{{ item | combine(postgresql) }}'
  vars:
    item:
      socket: /var/lib/mysql/mysql.sock
      client_cnf: /etc/my.cnf.d/client.cnf
      server_cnf: /etc/my.cnf.d/server.cnf
  when: os_type == "el7"


- name: set fact postgresql file for el
  set_fact:
    postgresql: '{{ item | combine(postgresql) }}'
  vars:
    item:
      socket: /var/lib/mysql/mysql.sock
      client_cnf: /etc/my.cnf.d/client.cnf
      server_cnf: /etc/my.cnf.d/postgresql-server.cnf
  when: os_type in ["el8", "el9"]

- name: set fact postgresql file for deb
  set_fact:
    postgresql: '{{ item | combine(postgresql) }}'
  vars:
    item:
      socket: /var/run/mysqld/mysqld.sock
      client_cnf: /etc/mysql/postgresql.conf.d/50-client.cnf
      server_cnf: /etc/mysql/postgresql.conf.d/50-server.cnf
  when: os_type is match("deb")
