- name: set fact postgresql
  set_fact:
    postgresql: '{{ {"type": ansible_pkg_mgr} | combine(postgresql, app.postgresql, recursive=True) }}'

- name: set fact postgresql file for el
  set_fact:
    postgresql: '{{ item | combine(postgresql) }}'
  vars:
    item:
      socket: /run/postgresql/.s.PGSQL.5432
      datadir: /var/lib/pgsql/data
  when: os_type in ["el8", "el9"]

- name: set fact postgresql file for deb
  set_fact:
    postgresql: '{{ item | combine(postgresql) }}'
  vars:
    item:
      socket: /run/postgresql/.s.PGSQL.5432
      datadir: /var/lib/pgsql/data
  when: os_type is match("deb")
