- name: dnf module install samba
  become: yes
  dnf:
    state: present
    name: '@samba:{{ samba.version }}'
  when: samba.type == "dnf" and samba.version is defined

- name: dnf install samba
  become: yes
  dnf:
    state: present
    name: samba
  when: samba.type == "dnf"

- name: apt install samba
  become: yes
  apt:
    state: present
    name: samba
  when: samba.type == "apt"
