- name: restart samba smb
  become: true
  systemd:
    name: smb.service
    daemon_reload: true
    enabled: true
    state: restarted

# - name: restart samba nmb
#   become: true
#   systemd:
#     name: nmb.service
#     daemon_reload: true
#     enabled: true
#     state: restarted
