# nginx.conf

- name: ngixn.conf user
  lineinfile:
    path: /usr/local/nginx/conf/nginx.conf
    regexp: '^[\s#]*user\b.*$'
    line: 'user nginx;'
    insertafter: '^[\s#]*user\b.*$'

- name: ngixn.conf worker_processes
  lineinfile:
    path: /usr/local/nginx/conf/nginx.conf
    regexp: '^[\s#]*worker_processes\b.*$'
    line: 'worker_processes auto;'
    insertafter: '^[\s#]*user\b.*$'

# 逆順に入れていく
- name: nginx.conf load_module
  lineinfile:
    path: /usr/local/nginx/conf/nginx.conf
    regexp: '^[\s#]load_module\s+\S+{{ item }}.so;.*$'
    line: 'load_module /usr/local/nginx/modules/{{ item }}.so;'
    insertafter: '^[\s#]*pid\b.*$'
  loop:
    - ngx_http_mruby_module
    - ndk_http_module
    - ngx_http_modsecurity_module
    - ngx_stream_module
    - ngx_mail_module

- name: ngixn.conf tcp_nopush
  replace:
    path: /usr/local/nginx/conf/nginx.conf
    after: '^\s*http\s+{'
    regexp: '^[\s#]*tcp_nopush\b.*$'
    replace: '    tcp_nopush on;'
