# nginx.conf

- name: nginx conf.d
  file:
    path: '{{ nginx_conf | dirname }}/conf.d'
    state: directory

- name: nginx default.d
  file:
    path: '{{ nginx_conf | dirname }}/default.d'
    state: directory

- name: nginx.conf
  template:
    src: ../files/nginx.conf.j2
    dest: '{{ nginx_conf }}'
