# nginx.conf

- name: nginx conf.d
  file:
    path: '{{ nginx_conf | dirname }}/conf.d'
    state: directory

- name: nginx copy conf
  copy:
    src: '../files/conf.d/{{ item }}.conf'
    dest: '{{ nginx_conf | dirname }}/conf.d/{{ item }}.conf'
  loop:
    - security

- name: nginx template conf
  template:
    src: '../files/conf.d/{{ item }}.conf.j2'
    dest: '{{ nginx_conf | dirname }}/conf.d/{{ item }}.conf'
  loop:
    - ssl

- name: nginx.conf user
  lineinfile:
    path: '{{ nginx_conf }}'
    regexp: '^[\s#]*user\b.*$'
    line: 'user {{ nginx.user }}{{ (nginx.user == nginx.group) | ternary("", " " ~ nginx.group)}};'
    insertbefore: BOF

- name: nginx.conf worker_processes
  lineinfile:
    path: '{{ nginx_conf }}'
    regexp: '^[\s#]*worker_processes\b.*$'
    line: 'worker_processes auto;'
    insertafter: '^[\s#]*user\b.*$'

- name: nginx.conf pid
  lineinfile:
    path: '{{ nginx_conf }}'
    regexp: '^[\s#]*pid\b.*$'
    line: 'pid {{ nginx.pid }};'
    insertafter: '^[\s#]*error_log\b.*$'
  when: nginx.pid is defined

- name: nginx.conf load_module
  lineinfile:
    path: '{{ nginx_conf }}'
    regexp: '^[\s#]load_module\s+(\S+/)?{{ item }}.so;.*$'
    line: 'load_module {{ nginx.modules | default("modules") }}/{{ item }}.so;'
    firstmatch: yes
    insertbefore: '^[\s#]*\w+\s*{.*$'
  loop:
    - ngx_mail_module
    - ngx_stream_module
    - ngx_http_modsecurity_module
    - ndk_http_module
    - ngx_http_mruby_module

- name: nginx.conf tcp_nopush
  lineinfile:
    path: '{{ nginx_conf }}'
    regexp: '^[\s#]*tcp_nopush\b.*$'
    line: '    tcp_nopush      on;'
    firstmatch: yes
    insertafter: '^\s*http\s*{'

- name: nginx.conf include http conf
  lineinfile:
    path: '{{ nginx_conf }}'
    regexp: '^[\s#]include\s+(\S+/)?{{ item }}.conf;.*$'
    line: '    include conf.d/{{ item }}.conf;'
    firstmatch: yes
    insertbefore: '^\s*server\s*{'
  loop:
    - security
    - ssl

- name: nginx.conf server listen 80 default_server
  lineinfile:
    path: '{{ nginx_conf }}'
    regexp: '^[\s]*listen\s+80\b.*$'
    line: '        listen       80 default_server;'
    firstmatch: yes
    insertafter: '^\s*server\s*{'

- name: nginx.conf server listen ipv6 80 default_server
  lineinfile:
    path: '{{ nginx_conf }}'
    regexp: '^[\s]*listen\s+\[::\]:80\b.*$'
    line: '        listen       [::]:80 default_server;'
    firstmatch: yes
    insertafter: '^[\s]*listen\s+80\b.*$'
 
- name: nginx.conf server server_name
  lineinfile:
    path: '{{ nginx_conf }}'
    regexp: '^[\s]*server_name\b.*$'
    line: '        server_name  _;'
    firstmatch: yes
    insertafter: '^\s*server\s*{'

- name: nginx.conf server return 301
  lineinfile:
    path: '{{ nginx_conf }}'
    regexp: '^[\s]*return\s+301\shttps://.*$'
    line: '        return       301 https://$host$request_uri;'
    firstmatch: yes
    insertbefore: '^\s*location\s+/\s*{'
