# geoipupdate
# https://github.com/maxmind/geoipupdate

- name: geoipupdate install
  dnf:
    name: 'https://github.com/maxmind/geoipupdate/releases/download/v{{ geoipupdate.version }}/geoipupdate_{{ geoipupdate.version }}_linux_amd64.rpm'
    state: present
    disable_gpg_check: yes
  environment: '{{ proxy.env | default({}) }}'

- name: geoipupdate config
  lineinfile:
    path: /etc/GeoIP.conf
    regexp: '^[\s#]*{{ item.name }}\b.*$'
    line: '{{ item.name }} {{ item.value }}'
  loop:
    - {name: AccountID, value: '{{ geoip.account_id }}'}
    - {name: LicenseKey, value: '{{ geoip.license_key }}'}

- name: geoipupdate config proxy
  lineinfile:
    path: /etc/GeoIP.conf
    regexp: '^[\s#]*{{ item.name }}\b.*$'
    line: '{{ item.name }} {{ item.value }}'
  loop:
    - {name: Proxy, value: '{{ proxy.host }}:{{ proxy.port }}'}
  when: proxy is defined

- name: run geoipupdate
  command: /usr/bin/geoipupdate

- name: crontab geoipupdate
  blockinfile:
    path: /etc/crontab
    marker: "# {mark} ANSIBLE MANAGED BLOCK geoipupdate"
    block: |
      {{ 60 | random }} 5 * * 0,3 root /usr/bin/geoipupdate >/dev/null 2>&1
