# nginx local
# localにインストールされるカスタマイズされたnginx
# nginx + modsecurity + mruby

# EL9のみ

- import_tasks: stop.yml

- import_tasks: selinux.yml

- import_tasks: package.yml

- import_tasks: modsecurity.yml

- import_tasks: nginx.yml

- import_tasks: setup.yml

- import_tasks: conf.yml

- import_tasks: start.yml

- import_tasks: firewall-firewalld.yml
  when: firewall_mgr == 'firewalld'

- import_tasks: firewall-ufw.yml
  when: firewall_mgr == 'ufw'
