# modsecurity and coreruleset

# modsecurity
# https://github.com/SpiderLabs/ModSecurity

- name: modsecurity get and unarchive
  unarchive:
    remote_src: yes
    src: 'https://github.com/SpiderLabs/ModSecurity/releases/download/v{{ modsecurity.version }}/modsecurity-v{{ modsecurity.version }}.tar.gz'
    dest: '{{ src_dir }}'
    creates: '{{ modsecurity_src }}'
  environment: '{{ proxy_env }}'

- name: modsecurity run build.sh
  command:
    cmd: sh ./build.sh
    chdir: '{{ modsecurity_src }}'

- name: modsecurity configure option
  set_fact:
    modsecurity_configure_option:
      - '{{ "--prefix=" ~ modsecurity.prefix if modsecurity.prefix is defined else None }}'
      - --with-lmdb
      - --with-pcre2

- name: modsecurity run configure
  command:
    argv: '{{ ["./configure"] + (modsecurity_configure_option | select() | list) }}'
    chdir: '{{ modsecurity_src }}'

- name: modsecurity run make
  command:
    cmd: make
    chdir: '{{ modsecurity_src }}'

- name: modsecurity run make insntall
  command:
    cmd: make install
    chdir: '{{ modsecurity_src }}'

- name: modsecurity mkdir conf diretory
  file:
    path: '{{ modsecurity_conf | dirname}}'
    state: directory

- name: modsecurity copy modsecurity.conf recommeded
  copy:
    remote_src: yes
    src: '{{ modsecurity_src }}/modsecurity.conf-recommended'
    dest: '{{ modsecurity_conf | dirname}}/modsecurity.conf'

- name: modsecurity copy unicode.mapping
  copy:
    remote_src: yes
    src: '{{ modsecurity_src }}/unicode.mapping'
    dest: '{{ modsecurity_conf | dirname}}/unicode.mapping'

# OWASP ModSecurity Core Rule Set
# https://coreruleset.org/

- name: coreruleset get and unarchive
  unarchive:
    remote_src: yes
    src: 'https://github.com/coreruleset/coreruleset/archive/refs/tags/v{{ coreruleset.version }}.tar.gz'
    dest: '{{ src_dir }}'
    creates: '{{ coreruleset_src }}'
  environment: '{{ proxy_env }}'

- name: coreruleset delete crs
  file:
    path: '{{ modsecurity_conf | dirname}}/crs'
    state: absent

- name: coreruleset copy crs
  copy:
    remote_src: yes
    src: '{{ coreruleset_src }}/'
    dest: '{{ modsecurity_conf | dirname}}/crs'

- name: coreruleset copy exapmle
  copy:
    remote_src: yes
    src: '{{ modsecurity_conf | dirname}}/crs/{{ item }}.example'
    dest: '{{ modsecurity_conf | dirname}}/crs/{{ item }}'
  loop:
    - crs-setup.conf
    - rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf
    - rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf

- name: modsecurity copy modsec_includes.conf
  copy:
    src: ../files/modsec_includes.conf
    dest: '{{ modsecurity_conf | dirname}}/modsec_includes.conf'

- name: modsecurity restorecon
  command: 'restorecon -irvF {{ modsecurity_prefix }}'
