# SE Linux

- name: dnf insntall
  dnf:
    state: present
    name: python3-policycoreutils

- name: SE Linux fcontext for modsecurity
  sefcontext:
    state: present
    target: '{{ item.target }}'
    ftype: '{{ item.ftype }}'
    setype: '{{ item.setype }}'
  loop:
  - {target: '/usr/local/modsecurity/bin',    ftype: a, setype: bin_t}
  - {target: '/usr/local/modsecurity/bin/.*', ftype: a, setype: bin_t}
  - {target: '/usr/local/modsecurity/lib',    ftype: a, setype: lib_t}
  - {target: '/usr/local/modsecurity/lib/.*', ftype: a, setype: lib_t}

- name: SE Linux fcontext for nginx
  sefcontext:
    state: present
    target: '{{ item.target }}'
    ftype: '{{ item.ftype }}'
    setype: '{{ item.setype }}'
  loop:
  - {target: '/usr/local/nginx/conf(/.*)?',       ftype: a, setype: httpd_config_t}
  - {target: '/usr/local/nginx/html(/.*)?',       ftype: a, setype: httpd_sys_content_t}
  - {target: '/var/local/nginx/logs(/.*)?',       ftype: a, setype: httpd_log_t}
  - {target: '/var/local/nginx/modules(/.*)?',    ftype: a, setype: lib_t}
  - {target: '/usr/local/nginx/sbin',             ftype: a, setype: bin_t}
  - {target: '/usr/local/nginx/sbin/.*',          ftype: a, setype: bin_t}
  - {target: '/usr/local/nginx/sbin/nginx',       ftype: f, setype: httpd_exec_t}
  - {target: '/var/log/nginx-local(/.*)?',        ftype: a, setype: httpd_log_t}
  - {target: '/var/run/nginx-local.*',            ftype: a, setype: httpd_var_run_t}
  - {target: '/var/lib/nginx-local(/.*)?',        ftype: a, setype: httpd_var_lib_t}
  # /etc/systemd/system = /usr/lib/systemd/system
  - {target: '/usr/lib/systemd/system/nginx-local.*', ftype: f, setype: httpd_unit_file_t}
