# SE Linux

- name: dnf insntall
  dnf:
    state: present
    name: python3-policycoreutils

- name: SE Linux fcontext for modsecurity
  sefcontext:
    state: present
    target: '{{ item.target }}'
    ftype: '{{ item.ftype }}'
    setype: '{{ item.setype }}'
  loop:
  - {target: '{{ modsecurity_prefix }}/bin(/.*)?', ftype: a, setype: bin_t}
  - {target: '{{ modsecurity_prefix }}/lib(/.*)?', ftype: a, setype: lib_t}
  - {target: '{{ modsecurity_conf | dirname }}(/.*)?', ftype: a, setype: etc_t}

- name: SE Linux fcontext for nginx
  sefcontext:
    state: present
    target: '{{ item.target }}'
    ftype: '{{ item.ftype }}'
    setype: '{{ item.setype }}'
  loop:
  - {target: '{{ nginx_conf | dirname }}(/.*)?', ftype: a, setype: httpd_config_t}
  - {target: '{{ nginx_html }}(/.*)?',           ftype: a, setype: httpd_sys_content_t}
  - {target: '{{ nginx_logs }}(/.*)?',           ftype: a, setype: httpd_log_t}
  - {target: '{{ nginx_modules }}(/.*)?',        ftype: a, setype: httpd_modules_t}
  - {target: '{{ nginx_sbin }}',                 ftype: f, setype: httpd_exec_t}
  - {target: '{{ nginx_pid | dirname }}(/.*)?',  ftype: a, setype: httpd_var_run_t}
  - {target: '{{ nginx_lock | dirname }}(/.*)?', ftype: a, setype: httpd_lock_t}
  - {target: '{{ nginx_temp }}(/.*)?',           ftype: a, setype: httpd_tmp_t}
  # /etc/systemd/system = /usr/lib/systemd/system
  - {target: '/usr/lib/systemd/system/nginx-local.*', ftype: f, setype: httpd_unit_file_t}
