# SE Linux

- name: fcontext
  sefcontext:
    state: present
    target: '{{ item.target }}'
    ftype: '{{ item.ftype }}'
    setype: '{{ item.setype }}'
  loop:
  - {target: '/usr/local/nginx/conf(/.*)?', ftype: a, setype: httpd_config_t}
  - {target: '/usr/lib/systemd/system/nginx-local.*', ftype: f, setype: httpd_unit_file_t}
  - {target: '/usr/local/nginx/sbin/nginx', ftype: f, setype: httpd_exec_t}

  - {target: '/var/lib/nginx(/.*)?', ftype: a, setype: httpd_var_lib_t}
  - {target: '/var/log/nginx(/.*)?', ftype: a, setype: httpd_log_t}
  - {target: '/var/run/nginx.*', ftype: a, setype: httpd_var_run_t}


  - {target: '/var/cache/nginx(/.*)?', ftype: a, setype: httpd_cache_t}

  - {target: '/usr/share/nginx/html(/.*)?', ftype: a, setype: httpd_sys_content_t}



  - {target: '/etc/opt/rh/rh-nginx18/nginx(/.*)?', ftype: a, setype: httpd_config_t}
  - {target: '/var/opt/rh/rh-nginx18/lib/nginx(/.*)?', ftype: a, setype: httpd_var_lib_t}
  - {target: '/var/opt/rh/rh-nginx18/log(/.*)?', ftype: a, setype: httpd_log_t}
  - {target: '/var/opt/rh/rh-nginx18/run/nginx(/.*)?', ftype: a, setype: httpd_var_run_t}
