# セットアップ

- name: nginx create group
  group:
    system: yes
    name: nginx

- name: nginx create user
  user:
    name: nginx
    system: yes
    home: /usr/local/nginx
    group: nginx
    shell: /sbin/nologin
    comment: Nginx web server
    create_home: no

- name: nginx logrotate file
  copy:
    src: ../files/nginx-local.logrotate
    dest: /etc/logrotate.d/nginx-local
