# セットアップ

- name: nginx create group
  group:
    system: yes
    name: '{{ nginx.group }}'

- name: nginx create user
  user:
    name: '{{ nginx.user }}'
    system: yes
    home: '{{ nginx_prefix }}'
    group: '{{ nginx.group }}'
    shell: /sbin/nologin
    comment: Nginx web server
    create_home: no

- name: nginx logrotate file
  template:
    src: ../files/nginx-local.logrotate.j2
    dest: /etc/logrotate.d/nginx-local
