- name: nginx service unit file
  template:
    src: ../files/nginx-local.service.j2
    dest: '/etc/systemd/system/{{ nginx.service }}'

- name: enable and restart nginx-local
  systemd:
    name: '{{ nginx.service }}'
    enabled: yes
    state: restarted
    daemon_reload: yes
