- name: copy .gemrc
  copy:
    src: ../files/.gemrc
    dest: /home/vagrant/.gemrc

- name: gem install packages
  gem:
    name: '{{ item }}'
    state: present
    user_install: no
  loop:
    - rubocop
    - yard
    - solargraph
    - slim_lint
  environment:
    GEM_HOME: /home/vagrant/.gem
  when: ruby_type is not defined or ruby_type != 'rbenv'

- name: gem install packages
  gem:
    name: '{{ item }}'
    state: present
    user_install: no
    executable: /home/vagrant/.rbenv/shims/gem
  loop:
    - rubocop
    - yard
    - solargraph
    - slim_lint
  when: ruby_type is defined and ruby_type == 'rbenv'
