- name: copy .gemrc
  copy:
    src: ../files/.gemrc
    dest: /home/vagrant/.gemrc

- name: gem install packages
  gem:
    name: '{{ item }}'
    state: present
    user_install: no
  loop: "{{ ruby.gems | default([]) }}"
  environment:
    GEM_HOME: /home/vagrant/.gem
  when: ruby.type is not defined or ruby.type != 'rbenv'

- name: gem install packages
  gem:
    name: '{{ item }}'
    state: present
    user_install: no
    executable: /home/vagrant/.rbenv/shims/gem
  loop: "{{ ruby.gems | default([]) }}"
  when: ruby.type is defined and ruby.type == 'rbenv'
