- name: apt install ruby
  become: yes
  apt:
    state: present
    name: ruby

- name: apt install ruby packages
  become: yes
  apt:
    state: present
    name: ruby-dev
  when: ruby.dev | default(False)

      - ruby-bundler

- name: apt install ruby modules (gems)
  become: yes
  apt:
    name: 'ruby-{{ item }}'
    state: present
  loop: '{{ ruby.mods | default([]) }}'
  when: ruby.mods is defined

- name: set PATH in .bashrc
  blockinfile:
    path: /home/vagrant/.bashrc
    marker: '# {mark} ANSIBLE MANAGED BLOCK ruby'
    block: |
      GEM_HOME="$HOME/.gem"
      export GEM_HOME
      if ! [[ "$PATH" =~ "$GEM_HOME/bin:" ]]
      then
          PATH="$GEM_HOME/bin:$PATH"
      fi
      export PATH
